import * as THREE from 'three';
import { deleteSavedProject, hasSavedProjects, listProjects, loadProject, saveProject } from '../persistence/storage.js';

export class AppUI {
  constructor(store){
    this.store=store;this.tree=document.querySelector('#object-tree');this.status=document.querySelector('#status');this.form=document.querySelector('#inspector');this.empty=document.querySelector('#inspector-empty');this.projectSelect=document.querySelector('#project-select');
    const q=id=>document.querySelector(id);this.fields={name:q('#object-name'),type:q('#object-type'),px:q('#pos-x'),py:q('#pos-y'),pz:q('#pos-z'),rx:q('#rot-x'),ry:q('#rot-y'),rz:q('#rot-z'),sx:q('#scale-x'),sy:q('#scale-y'),sz:q('#scale-z'),pvx:q('#pivot-x'),pvy:q('#pivot-y'),pvz:q('#pivot-z'),dx:q('#dim-x'),dy:q('#dim-y'),dz:q('#dim-z'),radius:q('#radius'),height:q('#height'),id:q('#object-id')};
    q('#new-project').addEventListener('click',()=>{if(confirm('Neues Projekt erstellen? Nicht gespeicherte Änderungen gehen verloren.')){this.store.newProject();this.setStatus('Neues Projekt erstellt.');}});
    q('#add-box').addEventListener('click',()=>this.created('Würfel',this.store.addBox()));q('#add-sphere').addEventListener('click',()=>this.created('Kugel',this.store.addSphere()));q('#add-cylinder').addEventListener('click',()=>this.created('Zylinder',this.store.addCylinder()));
    q('#group-selected').addEventListener('click',()=>{if(this.store.groupSelected())this.setStatus('Gruppe gebildet.');});q('#assembly-selected').addEventListener('click',()=>{if(this.store.assemblySelected())this.setStatus('Baugruppe gebildet.');});
    q('#save-project').addEventListener('click',()=>this.save());q('#load-project').addEventListener('click',()=>this.load());q('#delete-project').addEventListener('click',()=>this.deleteProject());
    q('#undo').addEventListener('click',()=>{if(this.store.undo())this.setStatus('Rückgängig.');});q('#redo').addEventListener('click',()=>{if(this.store.redo())this.setStatus('Wiederholt.');});q('#duplicate-object').addEventListener('click',()=>{if(this.store.duplicateSelected())this.setStatus('Objekt dupliziert.');});q('#delete-object').addEventListener('click',()=>{if(this.store.deleteSelected())this.setStatus('Auswahl gelöscht.');});
    for(const [id,mode] of [['tool-move','translate'],['tool-rotate','rotate'],['tool-scale','scale']])q(`#${id}`).addEventListener('click',()=>this.store.setToolMode(mode));
    this.fields.name.addEventListener('change',()=>{const id=this.store.selection.activeObjectId;if(id)this.store.setName(id,this.fields.name.value);});
    for(const input of [this.fields.px,this.fields.py,this.fields.pz,this.fields.rx,this.fields.ry,this.fields.rz,this.fields.sx,this.fields.sy,this.fields.sz])input.addEventListener('change',()=>this.commitTransform());
    for(const input of [this.fields.pvx,this.fields.pvy,this.fields.pvz])input.addEventListener('change',()=>this.commitPivot());
    for(const input of [this.fields.dx,this.fields.dy,this.fields.dz,this.fields.radius,this.fields.height])input.addEventListener('change',()=>this.commitGeometry());
    this.store.subscribe(event=>{if(['projectChanged','projectLoaded','objectCreated','objectChanged','geometryChanged','selectionChanged','historyChanged','toolChanged'].includes(event.type))this.render();});this.render();if(hasSavedProjects())this.setStatus('Gespeicherte Projekte vorhanden.');
  }
  created(label,id){this.setStatus(`${label} erzeugt: ${id}`);} save(){try{const r=saveProject(this.store.project);this.refreshProjects(r.projectId);this.setStatus(`Projekt gespeichert (${r.bytes} Zeichen).`);}catch(e){this.fail(e);}} load(){try{const id=this.projectSelect.value;if(!id)throw new Error('Bitte ein gespeichertes Projekt auswählen.');const p=loadProject(id);this.store.replaceProject(p);this.refreshProjects(id);this.setStatus(`Projekt geladen: ${p.project.name}`);}catch(e){this.fail(e);}} deleteProject(){const id=this.projectSelect.value;if(id&&confirm('Diesen gespeicherten Projektstand löschen?')){deleteSavedProject(id);this.refreshProjects();this.setStatus('Gespeicherter Projektstand gelöscht.');}}
  commitTransform(){const id=this.store.selection.activeObjectId;if(id)this.store.setTransformFromEuler(id,{position:{x:this.fields.px.value,y:this.fields.py.value,z:this.fields.pz.value},rotationDeg:{x:this.fields.rx.value,y:this.fields.ry.value,z:this.fields.rz.value},scale:{x:this.fields.sx.value,y:this.fields.sy.value,z:this.fields.sz.value}});}
  commitPivot(){const id=this.store.selection.activeObjectId;if(id)this.store.setPivot(id,{x:this.fields.pvx.value,y:this.fields.pvy.value,z:this.fields.pvz.value});}
  commitGeometry(){const id=this.store.selection.activeObjectId,o=this.store.getObject(id);if(!o)return;if(o.type==='primitive.box')this.store.setGeometry(id,{x:this.fields.dx.value,y:this.fields.dy.value,z:this.fields.dz.value});if(o.type==='primitive.sphere')this.store.setGeometry(id,{radius:this.fields.radius.value});if(o.type==='primitive.cylinder')this.store.setGeometry(id,{radius:this.fields.radius.value,height:this.fields.height.value});}
  render(){this.renderTree();this.renderInspector();this.renderToolbar();this.refreshProjects(this.projectSelect?.value);}
  renderToolbar(){const q=id=>document.querySelector(id);q('#undo').disabled=!this.store.undoStack.length;q('#redo').disabled=!this.store.redoStack.length;const has=!!this.store.selection.activeObjectId;q('#duplicate-object').disabled=!has;q('#delete-object').disabled=!this.store.selection.selectedObjectIds.length;const rootCount=this.store.selection.selectedObjectIds.filter(id=>this.store.getObject(id)?.parentId===null).length;q('#group-selected').disabled=!rootCount;q('#assembly-selected').disabled=!rootCount;for(const [id,mode] of [['tool-move','translate'],['tool-rotate','rotate'],['tool-scale','scale']])q(`#${id}`).classList.toggle('active',this.store.toolMode===mode);}
  refreshProjects(selectedId){if(!this.projectSelect)return;const current=selectedId||this.projectSelect.value;this.projectSelect.replaceChildren();const ph=document.createElement('option');ph.value='';ph.textContent='Gespeichertes Projekt wählen';this.projectSelect.appendChild(ph);for(const p of listProjects()){const o=document.createElement('option');o.value=p.projectId;o.textContent=`${p.name} – ${new Date(p.modifiedAt).toLocaleString()}`;this.projectSelect.appendChild(o);}if([...this.projectSelect.options].some(o=>o.value===current))this.projectSelect.value=current;}
  renderTree(){this.tree.replaceChildren();const objects=this.store.project.scene.objects,roots=this.store.project.scene.rootObjectIds.map(id=>objects[id]).filter(Boolean).sort((a,b)=>a.order-b.order);if(!roots.length){const p=document.createElement('div');p.className='muted';p.textContent='Noch keine Objekte';this.tree.appendChild(p);return;}for(const o of roots)this.tree.appendChild(this.treeNode(o,0));}
  treeNode(object,depth){const wrap=document.createElement('div');const row=document.createElement('div');row.className=`tree-item${object.objectId===this.store.selection.activeObjectId?' selected':''}`;row.style.paddingLeft=`${8+depth*16}px`;const cb=document.createElement('input');cb.type='checkbox';cb.className='tree-check';cb.checked=this.store.selection.selectedObjectIds.includes(object.objectId);cb.addEventListener('click',e=>{e.stopPropagation();this.store.select(object.objectId,true,true);});const label=document.createElement('span');label.textContent=`${typeIcon(object.type)} ${object.name}`;row.append(cb,label);row.title=object.objectId;row.addEventListener('click',()=>this.store.select(object.objectId));wrap.appendChild(row);const children=Object.values(this.store.project.scene.objects).filter(o=>o.parentId===object.objectId).sort((a,b)=>a.order-b.order);for(const child of children)wrap.appendChild(this.treeNode(child,depth+1));return wrap;}
  renderInspector(){const o=this.store.getObject(this.store.selection.activeObjectId);this.form.hidden=!o;this.empty.hidden=Boolean(o);if(!o)return;this.fields.name.value=o.name;this.fields.type.textContent=o.type;this.fields.id.textContent=o.objectId;const t=o.transform;this.fields.px.value=clean(t.position.x);this.fields.py.value=clean(t.position.y);this.fields.pz.value=clean(t.position.z);this.fields.sx.value=clean(t.scale.x);this.fields.sy.value=clean(t.scale.y);this.fields.sz.value=clean(t.scale.z);this.fields.pvx.value=clean(t.pivot.x);this.fields.pvy.value=clean(t.pivot.y);this.fields.pvz.value=clean(t.pivot.z);const e=new THREE.Euler().setFromQuaternion(new THREE.Quaternion(t.rotation.x,t.rotation.y,t.rotation.z,t.rotation.w),'XYZ');this.fields.rx.value=clean(THREE.MathUtils.radToDeg(e.x));this.fields.ry.value=clean(THREE.MathUtils.radToDeg(e.y));this.fields.rz.value=clean(THREE.MathUtils.radToDeg(e.z));const box=o.type==='primitive.box',sphere=o.type==='primitive.sphere',cyl=o.type==='primitive.cylinder';document.querySelector('#geometry-fields').hidden=!(box||sphere||cyl);document.querySelector('#dim-x-row').hidden=!box;document.querySelector('#dim-y-row').hidden=!box;document.querySelector('#dim-z-row').hidden=!box;document.querySelector('#radius-row').hidden=!(sphere||cyl);document.querySelector('#height-row').hidden=!cyl;if(box){this.fields.dx.value=clean(o.data.size.x);this.fields.dy.value=clean(o.data.size.y);this.fields.dz.value=clean(o.data.size.z);}if(sphere)this.fields.radius.value=clean(o.data.radius);if(cyl){this.fields.radius.value=clean(o.data.radius);this.fields.height.value=clean(o.data.height);}}
  setStatus(m){this.status.textContent=m;} fail(e){console.error(e);this.setStatus(e.message||String(e));alert(e.message||String(e));}
}
function clean(v){return Number(Number(v).toFixed(9));} function typeIcon(t){return t==='group'?'▾':t==='assembly'?'◆':t==='primitive.sphere'?'●':t==='primitive.cylinder'?'⬭':'■';}
