import * as THREE from 'three';
import { deleteSavedProject, hasSavedProjects, listProjects, loadProject, saveProject } from '../persistence/storage.js';

export class AppUI {
  constructor(store){this.store=store;const q=s=>document.querySelector(s);this.q=q;this.tree=q('#object-tree');this.status=q('#status');this.form=q('#inspector');this.empty=q('#inspector-empty');this.projectSelect=q('#project-select');this.parentSelect=q('#parent-select');this.fields={name:q('#object-name'),type:q('#object-type'),px:q('#pos-x'),py:q('#pos-y'),pz:q('#pos-z'),rx:q('#rot-x'),ry:q('#rot-y'),rz:q('#rot-z'),sx:q('#scale-x'),sy:q('#scale-y'),sz:q('#scale-z'),pvx:q('#pivot-x'),pvy:q('#pivot-y'),pvz:q('#pivot-z'),dx:q('#dim-x'),dy:q('#dim-y'),dz:q('#dim-z'),radius:q('#radius'),height:q('#height'),id:q('#object-id')};
    q('#new-project').onclick=()=>{if(confirm('Neues Projekt erstellen? Nicht gespeicherte Änderungen gehen verloren.')){store.newProject();this.setStatus('Neues Projekt erstellt.');}};
    q('#add-box').onclick=()=>this.created('Würfel',store.addBox());q('#add-sphere').onclick=()=>this.created('Kugel',store.addSphere());q('#add-cylinder').onclick=()=>this.created('Zylinder',store.addCylinder());q('#group-selected').onclick=()=>{if(store.groupSelected())this.setStatus('Gruppe gebildet.');};q('#assembly-selected').onclick=()=>{if(store.assemblySelected())this.setStatus('Baugruppe gebildet.');};q('#ungroup-selected').onclick=()=>{if(store.ungroupSelected())this.setStatus('Container aufgelöst.');};
    q('#save-project').onclick=()=>this.save();q('#load-project').onclick=()=>this.load();q('#delete-project').onclick=()=>this.deleteProject();q('#undo').onclick=()=>{if(store.undo())this.setStatus('Rückgängig.');};q('#redo').onclick=()=>{if(store.redo())this.setStatus('Wiederholt.');};q('#duplicate-object').onclick=()=>{if(store.duplicateSelected())this.setStatus('Objekt dupliziert.');};q('#delete-object').onclick=()=>{if(store.deleteSelected())this.setStatus('Auswahl gelöscht.');};
    for(const [id,mode] of [['#tool-move','translate'],['#tool-rotate','rotate'],['#tool-scale','scale']])q(id).onclick=()=>store.setToolMode(mode);q('#space-world').onclick=()=>store.setCoordinateSpace('world');q('#space-local').onclick=()=>store.setCoordinateSpace('local');q('#snap-enabled').onchange=e=>store.setSnapEnabled(e.target.checked);for(const [id,key] of [['#snap-move','translate'],['#snap-rotate','rotateDeg'],['#snap-scale','scale']])q(id).onchange=()=>store.setSnapValues({[key]:q(id).value});
    q('#pivot-center').onclick=()=>{const id=store.selection.activeObjectId;if(id)store.setPivotPreset(id,'center');};q('#pivot-bottom').onclick=()=>{const id=store.selection.activeObjectId;if(id)store.setPivotPreset(id,'bottom');};q('#apply-parent').onclick=()=>{const id=store.selection.activeObjectId;if(!id)return;const p=this.parentSelect.value||null;if(store.reparent(id,p))this.setStatus('Parent geändert, Weltlage erhalten.');};
    this.fields.name.onchange=()=>{const id=store.selection.activeObjectId;if(id)store.setName(id,this.fields.name.value);};for(const f of [this.fields.px,this.fields.py,this.fields.pz,this.fields.rx,this.fields.ry,this.fields.rz,this.fields.sx,this.fields.sy,this.fields.sz])f.onchange=()=>this.commitTransform();for(const f of [this.fields.pvx,this.fields.pvy,this.fields.pvz])f.onchange=()=>this.commitPivot();for(const f of [this.fields.dx,this.fields.dy,this.fields.dz,this.fields.radius,this.fields.height])f.onchange=()=>this.commitGeometry();
    store.subscribe(e=>{if(['projectChanged','projectLoaded','objectCreated','objectChanged','geometryChanged','selectionChanged','historyChanged','toolChanged','spaceChanged','snapChanged'].includes(e.type))this.render();});this.render();if(hasSavedProjects())this.setStatus('Gespeicherte Projekte vorhanden.');}
  created(label,id){this.setStatus(`${label} erzeugt: ${id}`);} save(){try{const r=saveProject(this.store.project);this.refreshProjects(r.projectId);this.setStatus(`Projekt gespeichert (${r.bytes} Zeichen).`);}catch(e){this.fail(e);}} load(){try{const id=this.projectSelect.value;if(!id)throw new Error('Bitte ein gespeichertes Projekt auswählen.');const p=loadProject(id);this.store.replaceProject(p);this.refreshProjects(id);this.setStatus(`Projekt geladen: ${p.project.name}`);}catch(e){this.fail(e);}} deleteProject(){const id=this.projectSelect.value;if(id&&confirm('Diesen gespeicherten Projektstand löschen?')){deleteSavedProject(id);this.refreshProjects();this.setStatus('Gespeicherter Projektstand gelöscht.');}}
  commitTransform(){const id=this.store.selection.activeObjectId;if(!id)return;const next={position:{x:this.fields.px.value,y:this.fields.py.value,z:this.fields.pz.value},rotationDeg:{x:this.fields.rx.value,y:this.fields.ry.value,z:this.fields.rz.value},scale:{x:this.fields.sx.value,y:this.fields.sy.value,z:this.fields.sz.value}};this.store.coordinateSpace==='world'?this.store.setWorldTransformFromEuler(id,next):this.store.setTransformFromEuler(id,next);}
  commitPivot(){const id=this.store.selection.activeObjectId;if(id)this.store.setPivot(id,{x:this.fields.pvx.value,y:this.fields.pvy.value,z:this.fields.pvz.value});}
  commitGeometry(){const id=this.store.selection.activeObjectId,o=this.store.getObject(id);if(!o)return;if(o.type==='primitive.box')this.store.setGeometry(id,{x:this.fields.dx.value,y:this.fields.dy.value,z:this.fields.dz.value});if(o.type==='primitive.sphere')this.store.setGeometry(id,{radius:this.fields.radius.value});if(o.type==='primitive.cylinder')this.store.setGeometry(id,{radius:this.fields.radius.value,height:this.fields.height.value});}
  render(){this.renderTree();this.renderInspector();this.renderToolbar();this.refreshProjects(this.projectSelect?.value);}
  renderToolbar(){const q=this.q,s=this.store;q('#undo').disabled=!s.undoStack.length;q('#redo').disabled=!s.redoStack.length;const active=s.getObject(s.selection.activeObjectId),has=!!active;q('#duplicate-object').disabled=!has;q('#delete-object').disabled=!s.selection.selectedObjectIds.length;const rootCount=s.selection.selectedObjectIds.filter(id=>s.getObject(id)?.parentId===null).length;q('#group-selected').disabled=!rootCount;q('#assembly-selected').disabled=!rootCount;q('#ungroup-selected').disabled=!active||!['group','assembly'].includes(active.type);for(const [id,mode] of [['#tool-move','translate'],['#tool-rotate','rotate'],['#tool-scale','scale']])q(id).classList.toggle('active',s.toolMode===mode);q('#space-world').classList.toggle('active',s.coordinateSpace==='world');q('#space-local').classList.toggle('active',s.coordinateSpace==='local');q('#snap-enabled').checked=s.snap.enabled;q('#snap-move').value=s.snap.translate;q('#snap-rotate').value=s.snap.rotateDeg;q('#snap-scale').value=s.snap.scale;for(const f of [this.fields.px,this.fields.py,this.fields.pz])f.step=s.snap.translate;for(const f of [this.fields.rx,this.fields.ry,this.fields.rz])f.step=s.snap.rotateDeg;for(const f of [this.fields.sx,this.fields.sy,this.fields.sz])f.step=s.snap.scale;}
  refreshProjects(selectedId){if(!this.projectSelect)return;const current=selectedId||this.projectSelect.value;this.projectSelect.replaceChildren(new Option('Gespeichertes Projekt wählen',''));for(const p of listProjects())this.projectSelect.appendChild(new Option(`${p.name} – ${new Date(p.modifiedAt).toLocaleString()}`,p.projectId));if([...this.projectSelect.options].some(o=>o.value===current))this.projectSelect.value=current;}
  renderTree(){this.tree.replaceChildren();const objects=this.store.project.scene.objects,roots=this.store.project.scene.rootObjectIds.map(id=>objects[id]).filter(Boolean).sort((a,b)=>a.order-b.order);if(!roots.length){const p=document.createElement('div');p.className='muted';p.textContent='Noch keine Objekte';this.tree.appendChild(p);return;}for(const o of roots)this.tree.appendChild(this.treeNode(o,0));}
  treeNode(o,depth){const wrap=document.createElement('div'),row=document.createElement('div');row.className=`tree-item${o.objectId===this.store.selection.activeObjectId?' selected':''}`;row.style.paddingLeft=`${8+depth*16}px`;const cb=document.createElement('input');cb.type='checkbox';cb.className='tree-check';cb.checked=this.store.selection.selectedObjectIds.includes(o.objectId);cb.onclick=e=>{e.stopPropagation();this.store.select(o.objectId,true,true);};const label=document.createElement('span');label.textContent=`${typeIcon(o.type)} ${o.name}`;row.append(cb,label);row.onclick=()=>this.store.select(o.objectId);wrap.appendChild(row);const children=Object.values(this.store.project.scene.objects).filter(x=>x.parentId===o.objectId).sort((a,b)=>a.order-b.order);for(const c of children)wrap.appendChild(this.treeNode(c,depth+1));return wrap;}
  renderInspector(){const o=this.store.getObject(this.store.selection.activeObjectId);this.form.hidden=!o;this.empty.hidden=!!o;if(!o)return;this.fields.name.value=o.name;this.fields.type.textContent=o.type;this.fields.id.textContent=o.objectId;this.parentSelect.replaceChildren(new Option('ROOT',''));for(const p of Object.values(this.store.project.scene.objects).filter(x=>x.objectId!==o.objectId&&this.store.canReparent(o.objectId,x.objectId)))this.parentSelect.appendChild(new Option(`${typeIcon(p.type)} ${p.name}`,p.objectId));this.parentSelect.value=o.parentId??'';const t=this.store.coordinateSpace==='world'?this.store.getWorldTransform(o.objectId):o.transform;this.q('#position-legend').textContent=`Position ${this.store.coordinateSpace.toUpperCase()} (m)`;this.q('#rotation-legend').textContent=`Rotation ${this.store.coordinateSpace.toUpperCase()} (°)`;this.fields.px.value=clean(t.position.x);this.fields.py.value=clean(t.position.y);this.fields.pz.value=clean(t.position.z);this.fields.sx.value=clean(t.scale.x);this.fields.sy.value=clean(t.scale.y);this.fields.sz.value=clean(t.scale.z);this.fields.pvx.value=clean(o.transform.pivot.x);this.fields.pvy.value=clean(o.transform.pivot.y);this.fields.pvz.value=clean(o.transform.pivot.z);const q=t.rotation,e=new THREE.Euler().setFromQuaternion(new THREE.Quaternion(q.x,q.y,q.z,q.w),'XYZ');this.fields.rx.value=clean(THREE.MathUtils.radToDeg(e.x));this.fields.ry.value=clean(THREE.MathUtils.radToDeg(e.y));this.fields.rz.value=clean(THREE.MathUtils.radToDeg(e.z));const box=o.type==='primitive.box',sphere=o.type==='primitive.sphere',cyl=o.type==='primitive.cylinder';this.q('#geometry-fields').hidden=!(box||sphere||cyl);this.q('#dim-x-row').hidden=!box;this.q('#dim-y-row').hidden=!box;this.q('#dim-z-row').hidden=!box;this.q('#radius-row').hidden=!(sphere||cyl);this.q('#height-row').hidden=!cyl;if(box){this.fields.dx.value=clean(o.data.size.x);this.fields.dy.value=clean(o.data.size.y);this.fields.dz.value=clean(o.data.size.z);}if(sphere)this.fields.radius.value=clean(o.data.radius);if(cyl){this.fields.radius.value=clean(o.data.radius);this.fields.height.value=clean(o.data.height);}}
  setStatus(m){this.status.textContent=m;}fail(e){console.error(e);this.setStatus(e.message||String(e));alert(e.message||String(e));}
}
function clean(v){return Number(Number(v).toFixed(9));}function typeIcon(t){return t==='group'?'▾':t==='assembly'?'◆':t==='primitive.sphere'?'●':t==='primitive.cylinder'?'⬭':'■';}
