import '../runtime-three/material-texture.js';
import { assignMaterialToObjects, createMaterial, importBaseColorTexture, materialBindingForObject, materialForObject, removeBaseColorTexture, removeMaterialFromObjects, setMaterialBaseColor, setMaterialMetallic, setMaterialOpacity, setMaterialRoughness, textureAssetForMaterial } from '../application/material.js';
import { addLibraryEntry, listLibraryEntries } from '../application/library-registry.js';
import { sharedLibraryRegistry } from '../application/library-runtime.js';
import { applyMaterialLibraryEntry, applyMaterialPreset, createMaterialLibraryEntry, MATERIAL_PRESETS } from '../application/material-library.js';

export function installMaterialPanel(store){
  const form=document.querySelector('#inspector');if(!form)return null;
  const registry=sharedLibraryRegistry;
  const panel=document.createElement('fieldset');panel.id='material-fields';panel.innerHTML='<legend>Material / Farbe</legend><label>Material <select id="material-select"></select></label><small id="material-selection-state"></small><label>Preset <select id="material-preset"></select></label><button id="material-preset-apply" type="button">Preset anwenden</button><label>Bibliothek <select id="material-library"></select></label><div class="button-row"><button id="material-library-save" type="button">Material merken</button><button id="material-library-apply" type="button">Bibliothek anwenden</button></div><label>Basisfarbe <input id="material-color" type="color" value="#b8bcc2"/></label><label>Metallisch <input id="material-metallic" type="number" min="0" max="1" step="0.01" value="0"/></label><label>Rauigkeit <input id="material-roughness" type="number" min="0" max="1" step="0.01" value="0.6"/></label><label>Transparenz / Opazität <input id="material-opacity" type="number" min="0" max="1" step="0.01" value="1"/></label><label>Basisfarbtextur <input id="material-texture-file" type="file" accept="image/png,image/jpeg,image/webp"/></label><small id="material-texture-state">Keine Textur</small><button id="material-texture-remove" type="button">Textur entfernen</button><div class="button-row"><button id="material-assign" type="button">Material zuweisen</button><button id="material-remove" type="button">Material entfernen</button><button id="material-new" type="button">Neues Material</button></div>';
  const idBox=form.querySelector('.id-box:last-child');form.insertBefore(panel,idBox??null);
  const select=panel.querySelector('#material-select'),state=panel.querySelector('#material-selection-state'),preset=panel.querySelector('#material-preset'),presetApply=panel.querySelector('#material-preset-apply'),library=panel.querySelector('#material-library'),librarySave=panel.querySelector('#material-library-save'),libraryApply=panel.querySelector('#material-library-apply'),color=panel.querySelector('#material-color'),metallic=panel.querySelector('#material-metallic'),roughness=panel.querySelector('#material-roughness'),opacity=panel.querySelector('#material-opacity'),textureFile=panel.querySelector('#material-texture-file'),textureState=panel.querySelector('#material-texture-state'),textureRemove=panel.querySelector('#material-texture-remove'),assign=panel.querySelector('#material-assign'),remove=panel.querySelector('#material-remove'),create=panel.querySelector('#material-new');
  for(const item of MATERIAL_PRESETS)preset.appendChild(new Option(`${item.category} · ${item.name}`,item.presetId));
  const selectedObjects=()=>store.selection.selectedObjectIds.map(id=>store.getObject(id)).filter(object=>object&&!['sketch','group','assembly','external.gltf'].includes(object.type));
  const renderLibrary=()=>{const current=library.value;library.replaceChildren();for(const entry of listLibraryEntries(registry,{entryKind:'material'}))library.appendChild(new Option(`${entry.category} · ${entry.name}`,entry.libraryEntryId));if([...library.options].some(o=>o.value===current))library.value=current;libraryApply.disabled=!library.value;};
  const applyMaterialValues=material=>{if(!material)return;if(material.properties?.baseColor)color.value=material.properties.baseColor;metallic.value=String(Number(material.properties?.metallic??0));roughness.value=String(Number(material.properties?.roughness??0.6));opacity.value=String(Number(material.properties?.opacity??1));const asset=textureAssetForMaterial(store,material.materialId);textureState.textContent=asset?asset.name||asset.assetId:'Keine Textur';textureRemove.disabled=!asset;};
  function render(){
    // Imported mesh controls are projected by imported-structure.js during the
    // inspector render. Its selection must not be hidden by the later listener.
    if(store.selection.importedElement)return;
    const objects=selectedObjects();panel.hidden=!objects.length;if(!objects.length)return;const bindings=objects.map(object=>materialBindingForObject(store,object.objectId)),keys=bindings.map(binding=>binding?`${binding.mode}:${binding.materialId}`:'none'),mixed=new Set(keys).size>1,currentId=!mixed?bindings[0]?.materialId??'':'';select.replaceChildren();for(const material of Object.values(store.project.materials??{}))select.appendChild(new Option(material.name||material.materialId,material.materialId));if(currentId&&[...select.options].some(o=>o.value===currentId))select.value=currentId;state.textContent=objects.length>1?(mixed?`${objects.length} Objekte · Gemischte Materialien`:`${objects.length} Objekte · Gemeinsames Material`):bindings[0]?.mode==='local'?'Lokale Materialvariante':'';applyMaterialValues(!mixed&&currentId?materialForObject(store,objects[0].objectId):store.project.materials?.[select.value]);renderLibrary();}
  select.onchange=()=>applyMaterialValues(store.project.materials?.[select.value]);assign.onclick=()=>{const r=assignMaterialToObjects(store,selectedObjects().map(o=>o.objectId),select.value);if(!r.ok)alert(r.message);};remove.onclick=()=>{const r=removeMaterialFromObjects(store,selectedObjects().map(o=>o.objectId));if(!r.ok)alert(r.message);};color.onchange=()=>{if(!select.value)return;const r=setMaterialBaseColor(store,select.value,color.value);if(!r.ok)alert(r.message);};const changeNumeric=(input,setter)=>{if(!select.value)return;const r=setter(store,select.value,input.value);if(!r.ok){alert(r.message);render();}};metallic.onchange=()=>changeNumeric(metallic,setMaterialMetallic);roughness.onchange=()=>changeNumeric(roughness,setMaterialRoughness);opacity.onchange=()=>changeNumeric(opacity,setMaterialOpacity);
  presetApply.onclick=()=>{const r=applyMaterialPreset(store,preset.value,selectedObjects().map(o=>o.objectId));if(!r.ok)alert(r.message);render();if(r.materialId)select.value=r.materialId;};
  librarySave.onclick=()=>{if(!select.value)return;const material=store.project.materials[select.value],name=prompt('Name für Materialbibliothek',material?.name??'Material');if(name==null)return;const category=prompt('Kategorie','Material');if(category==null)return;const made=createMaterialLibraryEntry(store,select.value,{name,category});if(!made.ok){alert(made.message);return;}const added=addLibraryEntry(registry,made.entry);if(!added.ok){alert(added.errors.join('\n'));return;}renderLibrary();library.value=made.entry.libraryEntryId;};
  libraryApply.onclick=()=>{const entry=registry.entries.find(item=>item.libraryEntryId===library.value);const r=applyMaterialLibraryEntry(store,entry,selectedObjects().map(o=>o.objectId));if(!r.ok)alert(r.message);render();if(r.materialId)select.value=r.materialId;};
  textureFile.onchange=()=>{const file=textureFile.files?.[0];if(!file||!select.value)return;const reader=new FileReader();reader.onload=()=>{const r=importBaseColorTexture(store,select.value,{name:file.name,mimeType:file.type,dataUrl:String(reader.result||'')});if(!r.ok)alert(r.message);textureFile.value='';render();};reader.onerror=()=>alert('Textur konnte nicht gelesen werden.');reader.readAsDataURL(file);};textureRemove.onclick=()=>{if(!select.value)return;const r=removeBaseColorTexture(store,select.value);if(!r.ok)alert(r.message);render();};
  create.onclick=()=>{const r=createMaterial(store,{name:`Material ${Object.keys(store.project.materials??{}).length+1}`,baseColor:color.value});if(!r.ok){alert(r.message);return;}const ids=selectedObjects().map(o=>o.objectId);if(ids.length)assignMaterialToObjects(store,ids,r.materialId);render();select.value=r.materialId;};store.subscribe(e=>{if(['selectionChanged','projectChanged','projectLoaded','objectCreated','historyChanged','materialChanged'].includes(e.type))render();});render();return {registry,render};
}

