import * as THREE from 'three';

const AXIS_LENGTH=0.5,AXIS_HEAD_LENGTH=0.12,AXIS_HEAD_RADIUS=0.045,PLANE_HANDLE_OFFSET=0.105,PLANE_HANDLE_SIZE=0.16,SNAP_EPS=1e-12;
const X_COLOR=0xff3b30,Y_COLOR=0x34c759,XY_COLOR=0xffd60a;

export function installSketchGizmo(store,runtime){
  const state={group:null,pickables:[],drag:null,previousEnableRotate:runtime.orbit.enableRotate,suppressNextSelectionAlign:false};
  const selected=()=>store.getSelectedSketchElements?.()??(store.selection.sketchElement?[store.selection.sketchElement]:[]);
  const primary=()=>selected().at(-1)??null;
  const sketch=()=>{const p=primary();return p?store.getObject(p.sketchId):null;};
  const uniquePointIds=(items,s)=>{const ids=new Set();for(const item of items){if(item.kind==='point')ids.add(item.elementId);else{const line=s.data?.lines?.[item.elementId];if(line){ids.add(line.startPointId);ids.add(line.endPointId);}}}return [...ids].filter(id=>s.data?.points?.[id]);};
  const anchorLocal=()=>{const items=selected(),s=sketch();if(!items.length||s?.type!=='sketch')return null;const ids=uniquePointIds(items,s);if(!ids.length)return null;const sum=ids.reduce((v,id)=>{const p=s.data.points[id];v.x+=p.x;v.y+=p.y;return v;},{x:0,y:0});return new THREE.Vector3(sum.x/ids.length,sum.y/ids.length,0);};
  const dispose=()=>{if(!state.group)return;state.group.traverse(n=>{n.geometry?.dispose?.();if(Array.isArray(n.material))n.material.forEach(m=>m?.dispose?.());else n.material?.dispose?.();});state.group.parent?.remove(state.group);state.group=null;state.pickables=[];};
  const alignCameraToSketch=()=>{const p=primary(),node=p?runtime.objectMap.get(p.sketchId):null,a=anchorLocal();if(!p||!node||!a)return false;node.updateWorldMatrix(true,false);const target=node.localToWorld(a.clone()),normal=new THREE.Vector3(0,0,1).transformDirection(node.matrixWorld).normalize(),up=new THREE.Vector3(0,1,0).transformDirection(node.matrixWorld).normalize(),distance=Math.max(runtime.camera.position.distanceTo(runtime.orbit.target),0.25);runtime.orbit.target.copy(target);runtime.camera.up.copy(up);runtime.camera.position.copy(target).addScaledVector(normal,distance);runtime.camera.lookAt(target);runtime.orbit.update();runtime.updateCameraRange?.();runtime.updateGrid?.();return true;};
  const makeAxis=axis=>{const g=new THREE.Group(),dir=axis==='x'?new THREE.Vector3(1,0,0):new THREE.Vector3(0,1,0),color=axis==='x'?X_COLOR:Y_COLOR;const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(),dir.clone().multiplyScalar(AXIS_LENGTH-AXIS_HEAD_LENGTH*.45)]),new THREE.LineBasicMaterial({color,depthTest:false}));line.renderOrder=1000;g.add(line);const cone=new THREE.Mesh(new THREE.ConeGeometry(AXIS_HEAD_RADIUS,AXIS_HEAD_LENGTH,16),new THREE.MeshBasicMaterial({color,depthTest:false}));cone.position.copy(dir).multiplyScalar(AXIS_LENGTH);cone.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dir);cone.renderOrder=1001;g.add(cone);const hit=new THREE.Mesh(new THREE.BoxGeometry(axis==='x'?AXIS_LENGTH+.12:.18,axis==='y'?AXIS_LENGTH+.12:.18,.1),new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false}));hit.position.copy(dir).multiplyScalar(AXIS_LENGTH/2);hit.userData.cm3dSketchGizmoAxis=axis;g.add(hit);state.pickables.push(hit);return g;};
  const makePlane=()=>{const g=new THREE.Group(),pos=PLANE_HANDLE_OFFSET+PLANE_HANDLE_SIZE/2,fill=new THREE.Mesh(new THREE.PlaneGeometry(PLANE_HANDLE_SIZE,PLANE_HANDLE_SIZE),new THREE.MeshBasicMaterial({color:XY_COLOR,transparent:true,opacity:.42,depthTest:false,side:THREE.DoubleSide}));fill.position.set(pos,pos,0);fill.renderOrder=1002;g.add(fill);const hit=new THREE.Mesh(new THREE.PlaneGeometry(PLANE_HANDLE_SIZE+.08,PLANE_HANDLE_SIZE+.08),new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false,side:THREE.DoubleSide}));hit.position.copy(fill.position);hit.userData.cm3dSketchGizmoAxis='xy';g.add(hit);state.pickables.push(hit);return g;};
  const rebuildGizmo=(align=true)=>{dispose();const p=primary(),node=p?runtime.objectMap.get(p.sketchId):null;if(!p||!node){runtime.orbit.enableRotate=state.previousEnableRotate;return;}if(align)alignCameraToSketch();runtime.orbit.enableRotate=false;const a=anchorLocal();if(!a)return;const g=new THREE.Group();g.name='CM3D_SKETCH_GIZMO';g.add(makeAxis('x'),makeAxis('y'),makePlane());node.add(g);g.position.copy(a);state.group=g;};
  const localPoint=(event,sketchId)=>{const node=runtime.objectMap.get(sketchId);if(!node)return null;node.updateWorldMatrix(true,false);runtime.pointerFromEvent(event);const origin=node.getWorldPosition(new THREE.Vector3()),normal=new THREE.Vector3(0,0,1).transformDirection(node.matrixWorld),plane=new THREE.Plane().setFromNormalAndCoplanarPoint(normal,origin),world=new THREE.Vector3();if(!runtime.raycaster.ray.intersectPlane(plane,world))return null;return node.worldToLocal(world.clone());};
  const snap=v=>{if(!store.snap.enabled)return v;const step=Number(store.snap.translate);return Number.isFinite(step)&&step>SNAP_EPS?Math.round(v/step)*step:v;};
  const startDrag=event=>{if(!state.pickables.length)return false;runtime.pointerFromEvent(event);const hit=runtime.raycaster.intersectObjects(state.pickables,false)[0],items=selected(),p=primary(),s=sketch();if(!hit||!items.length||!p||s?.type!=='sketch')return false;const start=localPoint(event,p.sketchId);if(!start)return false;const ids=uniquePointIds(items,s),initial={};for(const id of ids){const pt=s.data.points[id];initial[id]={x:pt.x,y:pt.y};}state.drag={pointerId:event.pointerId,sketchId:p.sketchId,items:structuredClone(items),axis:hit.object.userData.cm3dSketchGizmoAxis,start:{x:start.x,y:start.y},initial,anchor:anchorLocal(),before:store.snapshot()};runtime.orbit.enabled=false;runtime.renderer.domElement.setPointerCapture?.(event.pointerId);event.preventDefault();event.stopImmediatePropagation();return true;};
  const updateDrag=event=>{const d=state.drag;if(!d||event.pointerId!==d.pointerId)return;const s=store.getObject(d.sketchId),p=localPoint(event,d.sketchId);if(s?.type!=='sketch'||!p)return;let dx=p.x-d.start.x,dy=p.y-d.start.y;if(d.axis==='x')dy=0;if(d.axis==='y')dx=0;const sx=snap(d.anchor.x+dx)-d.anchor.x,sy=snap(d.anchor.y+dy)-d.anchor.y;for(const [id,start] of Object.entries(d.initial)){const pt=s.data.points?.[id];if(pt){pt.x=start.x+sx;pt.y=start.y+sy;}}store.refreshDependentExtrudesFromSketch?.(d.sketchId);store.touch();runtime.rebuild();store.emit('sketchGizmoPreview',{sketchId:d.sketchId,count:d.items.length});rebuildGizmo(false);event.preventDefault();event.stopImmediatePropagation();};
  const finishDrag=event=>{const d=state.drag;if(!d||event.pointerId!==d.pointerId)return;state.drag=null;runtime.renderer.domElement.releasePointerCapture?.(event.pointerId);runtime.orbit.enabled=true;runtime.orbit.enableRotate=false;const after=store.snapshot();if(JSON.stringify(d.before)!==JSON.stringify(after))store.pushHistory(d.before,d.items.length>1?'Skizzenauswahl per Gizmo verschieben':d.items[0]?.kind==='point'?'Skizzenpunkt per Gizmo verschieben':'Skizzenlinie per Gizmo verschieben');state.suppressNextSelectionAlign=true;store.emit('geometryChanged',{objectId:d.sketchId,sketchDependencySynced:true});store.emit('selectionChanged');rebuildGizmo(false);event.preventDefault();event.stopImmediatePropagation();};
  const canvas=runtime.renderer.domElement;canvas.addEventListener('pointerdown',startDrag,true);window.addEventListener('pointermove',updateDrag,true);window.addEventListener('pointerup',finishDrag,true);window.addEventListener('pointercancel',finishDrag,true);
  store.subscribe(event=>{if(!['selectionChanged','projectChanged','projectLoaded','geometryChanged','objectChanged'].includes(event.type)||state.drag)return;let align=event.type==='selectionChanged';if(align&&state.suppressNextSelectionAlign){align=false;state.suppressNextSelectionAlign=false;}setTimeout(()=>rebuildGizmo(align),0);});
  document.title='CyberMotion 3D – WD-12B';const label=document.querySelector('.brand small');if(label)label.textContent='WD-12B';rebuildGizmo();return{alignCameraToSketch,rebuildGizmo};
}
