import { createLibraryEntry } from './library-registry.js';

const uuid=prefix=>`${prefix}_${crypto.randomUUID()}`;
const CONTAINER_TYPES=new Set(['group','assembly']);
const LEAF_TYPES=new Set(['primitive.box','primitive.sphere','primitive.cylinder','external.gltf']);
const assetById=(project,id)=>project?.assets?.find(asset=>asset.assetId===id)??null;
const childrenOf=(project,parentId)=>Object.values(project?.scene?.objects??{}).filter(object=>object.parentId===parentId).sort((a,b)=>(a.order??0)-(b.order??0)||a.objectId.localeCompare(b.objectId));

function collectTree(project,root){const result=[];const visit=object=>{result.push(object);for(const child of childrenOf(project,object.objectId))visit(child);};visit(root);return result;}
function hasUnsupportedReference(object){const data=object.data??{};return !!(data.sourceRef||data.sourceSketchRef||(Array.isArray(data.sourceProfileRefs)&&data.sourceProfileRefs.length)||data.planeRef||data.workPlaneRef||data.sourceObjectId);}

function portableTexture(project,assetId,key){const asset=assetById(project,assetId);if(!asset||asset.kind!=='image.texture')throw new Error(`Textur-Asset ${assetId} fehlt oder ist ungültig.`);return {libraryAssetKey:key,kind:'image.texture',format:asset.format,mimeType:asset.mimeType,name:asset.name,dataUrl:asset.dataUrl};}
function portableMaterial(project,materialId,key,textureKeys,textures){const material=project?.materials?.[materialId];if(!material)throw new Error(`Material ${materialId} fehlt.`);const textureRefs={};const textureId=material.textureRefs?.baseColor;if(textureId){let textureKey=textureKeys.get(textureId);if(!textureKey){textureKey=`texture:${textureKeys.size}`;textureKeys.set(textureId,textureKey);textures.push(portableTexture(project,textureId,textureKey));}textureRefs.baseColor=textureKey;}return {libraryMaterialKey:key,name:material.name??'Material',type:material.type??'pbr.standard',properties:structuredClone(material.properties??{}),textureRefs,extensions:structuredClone(material.extensions??{})};}
function portableModel(project,assetId,key){const asset=assetById(project,assetId);if(!asset||asset.kind!=='model.gltf.bundle')throw new Error(`GLTF-Modellasset ${assetId} fehlt oder ist ungültig.`);return {libraryAssetKey:key,kind:asset.kind,format:asset.format,name:asset.name,entryFile:asset.entryFile,files:structuredClone(asset.files??[])};}

export function createAssemblyLibraryEntry(store,rootId,{name=null,category='Assembly'}={}){
  const project=store?.project,root=store?.getObject?.(rootId)??project?.scene?.objects?.[rootId];if(!root)return {ok:false,message:'Baugruppen-Root fehlt.'};if(!CONTAINER_TYPES.has(root.type))return {ok:false,message:'Nur group/assembly kann als Baugruppenvorlage gespeichert werden.'};
  try{const tree=collectTree(project,root),ids=new Set(tree.map(o=>o.objectId));for(const object of tree){if(!CONTAINER_TYPES.has(object.type)&&!LEAF_TYPES.has(object.type))throw new Error(`Objekttyp ${object.type} ist in WD-26I nicht portabel.`);if(hasUnsupportedReference(object))throw new Error(`Objekt ${object.name??object.objectId} besitzt nicht unterstützte externe Abhängigkeiten.`);if(object!==root&&!ids.has(object.parentId))throw new Error('Teilbaum enthält eine externe Parent-Referenz.');}
    const objectKeys=new Map(tree.map((object,index)=>[object.objectId,`object:${index}`])),materialKeys=new Map(),textureKeys=new Map(),modelKeys=new Map(),materials=[],textures=[],models=[];
    const portableObjects=tree.map(object=>{const materialRefs=(object.materialIds??[]).map(materialId=>{let key=materialKeys.get(materialId);if(!key){key=`material:${materialKeys.size}`;materialKeys.set(materialId,key);materials.push(portableMaterial(project,materialId,key,textureKeys,textures));}return key;});let materialBinding=null;if(object.materialBinding){const materialKey=materialKeys.get(object.materialBinding.materialId);if(!materialKey)throw new Error('MaterialBinding verweist außerhalb der portablen Materialmenge.');materialBinding={mode:object.materialBinding.mode,materialKey};if(object.materialBinding.mode==='local'){const sourceMaterialKey=materialKeys.get(object.materialBinding.sourceMaterialId);if(!sourceMaterialKey)throw new Error('Local-Variant-Quelle liegt außerhalb der portablen Materialmenge.');materialBinding.sourceMaterialKey=sourceMaterialKey;}}
      const data=structuredClone(object.data??{});if(object.type==='external.gltf'){let modelKey=modelKeys.get(data.assetId);if(!modelKey){modelKey=`model:${modelKeys.size}`;modelKeys.set(data.assetId,modelKey);models.push(portableModel(project,data.assetId,modelKey));}data.assetId=modelKey;}
      return {objectKey:objectKeys.get(object.objectId),parentKey:object===root?null:objectKeys.get(object.parentId),type:object.type,name:object.name,order:object.order??0,transform:structuredClone(object.transform),data,materialKeys:materialRefs,materialBinding,flags:structuredClone(object.flags??{}),extensions:structuredClone(object.extensions??{})};});
    const result=createLibraryEntry({entryKind:'assembly',name:name??root.name??'Baugruppe',category,payload:{rootKey:objectKeys.get(root.objectId),objects:portableObjects,materials,textures,models}});return result.ok?result:{ok:false,message:result.errors.join('\n')};
  }catch(error){return {ok:false,message:error?.message??String(error)};}
}

function instantiateTexture(store,asset){if(asset.kind!=='image.texture'||typeof asset.dataUrl!=='string'||!asset.dataUrl.startsWith(`data:${asset.mimeType};base64,`))throw new Error('Portable Materialtextur ist ungültig.');const assetId=uuid('asset');store.project.assets.push({assetId,kind:asset.kind,format:asset.format,mimeType:asset.mimeType,name:asset.name,dataUrl:asset.dataUrl});return assetId;}
function instantiateModel(store,asset){if(asset.kind!=='model.gltf.bundle'||!['glb','gltf'].includes(asset.format)||!asset.entryFile||!Array.isArray(asset.files)||!asset.files.length)throw new Error('Portables GLTF-Modellasset ist ungültig.');const assetId=uuid('asset');store.project.assets.push({assetId,kind:asset.kind,format:asset.format,name:asset.name,entryFile:asset.entryFile,files:structuredClone(asset.files)});return assetId;}

export function insertAssemblyLibraryEntry(store,entry){
  if(!entry||entry.entryKind!=='assembly'||!entry.payload?.rootKey||!Array.isArray(entry.payload.objects))return {ok:false,message:'Assembly-LibraryEntry ist ungültig.'};const before=store.snapshot();try{store.project.assets??=[];const textureMap=new Map(),modelMap=new Map(),materialMap=new Map(),objectMap=new Map();for(const asset of entry.payload.textures??[])textureMap.set(asset.libraryAssetKey,instantiateTexture(store,asset));for(const asset of entry.payload.models??[])modelMap.set(asset.libraryAssetKey,instantiateModel(store,asset));for(const definition of entry.payload.materials??[]){const materialId=uuid('mat'),textureRefs={};if(definition.textureRefs?.baseColor){const textureId=textureMap.get(definition.textureRefs.baseColor);if(!textureId)throw new Error('Materialtextur kann nicht aufgelöst werden.');textureRefs.baseColor=textureId;}store.project.materials[materialId]={materialId,name:definition.name,type:definition.type,properties:structuredClone(definition.properties??{}),textureRefs,extensions:structuredClone(definition.extensions??{})};materialMap.set(definition.libraryMaterialKey,materialId);}for(const source of entry.payload.objects)objectMap.set(source.objectKey,uuid('obj'));
    const created=[];for(const source of entry.payload.objects){if(!CONTAINER_TYPES.has(source.type)&&!LEAF_TYPES.has(source.type))throw new Error(`Objekttyp ${source.type} ist nicht portabel.`);const objectId=objectMap.get(source.objectKey),parentId=source.parentKey==null?null:objectMap.get(source.parentKey);if(source.parentKey!=null&&!parentId)throw new Error('Parent-Referenz kann nicht aufgelöst werden.');const data=structuredClone(source.data??{});if(source.type==='external.gltf'){const assetId=modelMap.get(data.assetId);if(!assetId)throw new Error('GLTF-Asset kann nicht aufgelöst werden.');data.assetId=assetId;}const materialIds=(source.materialKeys??[]).map(key=>{const id=materialMap.get(key);if(!id)throw new Error('Material kann nicht aufgelöst werden.');return id;});const object={objectId,type:source.type,name:source.objectKey===entry.payload.rootKey?(entry.name??source.name):source.name,parentId,order:source.order??0,layerId:null,transform:structuredClone(source.transform),data,materialIds,flags:structuredClone(source.flags??{visible:true,locked:false}),extensions:structuredClone(source.extensions??{})};if(source.materialBinding){const materialId=materialMap.get(source.materialBinding.materialKey);if(!materialId)throw new Error('MaterialBinding kann nicht aufgelöst werden.');object.materialBinding={mode:source.materialBinding.mode,materialId};if(source.materialBinding.mode==='local'){const sourceMaterialId=materialMap.get(source.materialBinding.sourceMaterialKey);if(!sourceMaterialId)throw new Error('Local-Variant-Quelle kann nicht aufgelöst werden.');object.materialBinding.sourceMaterialId=sourceMaterialId;}}store.project.scene.objects[objectId]=object;created.push(objectId);}
    const rootId=objectMap.get(entry.payload.rootKey);if(!rootId)throw new Error('Assembly-Root kann nicht aufgelöst werden.');store.project.scene.rootObjectIds.push(rootId);store.touch();store.pushHistory(before,'Baugruppe aus Bibliothek einfügen');for(const objectId of created)store.emit('objectCreated',{objectId});store.select?.(rootId);return {ok:true,rootId,objectIds:created};
  }catch(error){store.project=before;return {ok:false,message:error?.message??String(error)};}
}
