import { ReferenceTargetKind, ReferenceState, resolveStableReference } from './stable-reference.js';
import { ConstructionReferenceObjectType, SYSTEM_CONSTRUCTION_OWNER_ID } from '../model/construction-reference.js';

export const DependencyNodeState = Object.freeze({ READY:'READY', MISSING:ReferenceState.MISSING, INVALID:ReferenceState.INVALID, BLOCKED:ReferenceState.BLOCKED });
const cloneRef=ref=>ref?{...ref}:null; const cloneDiagnostic=item=>({...item});
const addEdge=(outgoing,incoming,edge)=>{if(!outgoing.has(edge.sourceObjectId))outgoing.set(edge.sourceObjectId,[]);if(!incoming.has(edge.dependentObjectId))incoming.set(edge.dependentObjectId,[]);outgoing.get(edge.sourceObjectId).push(edge);incoming.get(edge.dependentObjectId).push(edge);};
const resolvedEdgesOnly=edges=>(edges??[]).filter(edge=>edge?.state===ReferenceState.RESOLVED);
const dependencySourceObjectId=reference=>{if(!reference)return null;if([ReferenceTargetKind.PROFILE,ReferenceTargetKind.PATH,ReferenceTargetKind.WORK_PLANE,ReferenceTargetKind.CONSTRUCTION_AXIS,ReferenceTargetKind.PLANAR_FACE,ReferenceTargetKind.FEATURE_OUTPUT].includes(reference.targetKind)){if(reference.ownerId===SYSTEM_CONSTRUCTION_OWNER_ID)return null;return reference.ownerId??null;}return reference.targetId??null;};
export function createDependencyEdge(store,dependentObjectId,reference,kind='GENERIC_REFERENCE'){if(!dependentObjectId||!reference)return null;const sourceObjectId=dependencySourceObjectId(reference);if(!sourceObjectId)return null;const resolution=resolveStableReference(store,reference);return{sourceObjectId,dependentObjectId,kind,reference:cloneRef(reference),state:resolution.state,diagnostics:resolution.diagnostics.map(cloneDiagnostic)};}
export function detectDependencyCycles(edges=[]){const adjacency=new Map(),nodeIds=new Set();for(const edge of resolvedEdgesOnly(edges)){nodeIds.add(edge.sourceObjectId);nodeIds.add(edge.dependentObjectId);if(!adjacency.has(edge.sourceObjectId))adjacency.set(edge.sourceObjectId,[]);adjacency.get(edge.sourceObjectId).push(edge.dependentObjectId);}for(const targets of adjacency.values())targets.sort((a,b)=>a.localeCompare(b));let index=0;const indices=new Map(),lowLinks=new Map(),stack=[],onStack=new Set(),cycles=[];const strongConnect=nodeId=>{indices.set(nodeId,index);lowLinks.set(nodeId,index++);stack.push(nodeId);onStack.add(nodeId);for(const dependentId of adjacency.get(nodeId)??[]){if(!indices.has(dependentId)){strongConnect(dependentId);lowLinks.set(nodeId,Math.min(lowLinks.get(nodeId),lowLinks.get(dependentId)));}else if(onStack.has(dependentId))lowLinks.set(nodeId,Math.min(lowLinks.get(nodeId),indices.get(dependentId)));}if(lowLinks.get(nodeId)!==indices.get(nodeId))return;const component=[];while(stack.length){const member=stack.pop();onStack.delete(member);component.push(member);if(member===nodeId)break;}component.sort((a,b)=>a.localeCompare(b));const selfCycle=component.length===1&&(adjacency.get(component[0])??[]).includes(component[0]);if(component.length>1||selfCycle)cycles.push(component);};for(const nodeId of [...nodeIds].sort((a,b)=>a.localeCompare(b)))if(!indices.has(nodeId))strongConnect(nodeId);return cycles.sort((a,b)=>a.join('\u0000').localeCompare(b.join('\u0000')));}
export function wouldCreateDependencyCycle(graph,sourceObjectId,dependentObjectId){if(!sourceObjectId||!dependentObjectId)return false;if(sourceObjectId===dependentObjectId)return true;const visited=new Set(),pending=[dependentObjectId];while(pending.length){const current=pending.shift();if(current===sourceObjectId)return true;if(visited.has(current))continue;visited.add(current);pending.push(...(graph?.dependentsOf?.(current)??[]).filter(edge=>edge.state===ReferenceState.RESOLVED).map(edge=>edge.dependentObjectId).sort((a,b)=>a.localeCompare(b)));}return false;}
export function validateDependencyEdge(graph,sourceObjectId,dependentObjectId){if(!sourceObjectId||!dependentObjectId)return{allowed:false,code:'DEPENDENCY_ENDPOINT_MISSING',message:'Dependency-Kante benötigt Quelle und abhängiges Ziel.'};if(wouldCreateDependencyCycle(graph,sourceObjectId,dependentObjectId))return{allowed:false,code:'DEPENDENCY_CYCLE',message:`Dependency-Kante ${sourceObjectId} → ${dependentObjectId} würde einen Zyklus erzeugen.`};return{allowed:true,code:null,message:null};}
const markBlocked=(node,state,diagnostics=[],message='Abhängige Berechnung ist blockiert, weil die Quellreferenz nicht auflösbar ist.')=>{node.state=DependencyNodeState.BLOCKED;node.upstreamState=state;node.diagnostics.push({code:`UPSTREAM_${state}`,message},...diagnostics.map(cloneDiagnostic));};
export function buildDependencyGraph(store,declaredDependencies=[]){const nodes=new Map(),outgoing=new Map(),incoming=new Map();for(const object of Object.values(store?.project?.scene?.objects??{}))nodes.set(object.objectId,{objectId:object.objectId,objectType:object.type,state:DependencyNodeState.READY,upstreamState:null,diagnostics:[]});
for(const object of Object.values(store?.project?.scene?.objects??{})){if(object?.type!==ConstructionReferenceObjectType.WORK_PLANE||!object.data?.derivation?.sourceRef)continue;const node=nodes.get(object.objectId),edge=createDependencyEdge(store,object.objectId,object.data.derivation.sourceRef,'PLANE_REFERENCE_TO_DERIVED_WORK_PLANE');if(edge)addEdge(outgoing,incoming,edge);if(!edge||edge.state!==ReferenceState.RESOLVED)markBlocked(node,edge?.state??ReferenceState.INVALID,edge?.diagnostics??[]);}
for(const object of Object.values(store?.project?.scene?.objects??{})){if(object?.type!=='sketch'||!object.data?.planeRef)continue;const node=nodes.get(object.objectId),resolution=resolveStableReference(store,object.data.planeRef),edge=createDependencyEdge(store,object.objectId,object.data.planeRef,'PLANE_REFERENCE_TO_SKETCH');if(edge)addEdge(outgoing,incoming,edge);if(resolution.state!==ReferenceState.RESOLVED)markBlocked(node,resolution.state,resolution.diagnostics);}
for(const object of Object.values(store?.project?.scene?.objects??{})){if(object?.type!=='feature.extrude')continue;const node=nodes.get(object.objectId),profileRefs=Array.isArray(object.data?.sourceProfileRefs)?object.data.sourceProfileRefs:[],refs=profileRefs.length?profileRefs:[object.data?.sourceSketchRef].filter(Boolean),kind=profileRefs.length?'PROFILE_TO_EXTRUDE':'SKETCH_TO_EXTRUDE';if(!refs.length){node.state=DependencyNodeState.MISSING;node.diagnostics.push({code:'SOURCE_REFERENCE_MISSING',message:'Extrusion besitzt keine stabile Quellreferenz.'});continue;}for(const ref of refs){const edge=createDependencyEdge(store,object.objectId,ref,kind);if(edge)addEdge(outgoing,incoming,edge);if(!edge||edge.state!==ReferenceState.RESOLVED)markBlocked(node,edge?.state??ReferenceState.INVALID,edge?.diagnostics??[]);}}
for(const object of Object.values(store?.project?.scene?.objects??{})){if(object?.type!=='feature.thin-extrude')continue;const node=nodes.get(object.objectId),ref=object.data?.sourceRef;if(!ref){node.state=DependencyNodeState.MISSING;node.diagnostics.push({code:'SOURCE_REFERENCE_MISSING',message:'Thin Extrude besitzt keine stabile PATH-Referenz.'});continue;}const edge=createDependencyEdge(store,object.objectId,ref,'PATH_TO_THIN_EXTRUDE');if(edge)addEdge(outgoing,incoming,edge);if(!edge||edge.state!==ReferenceState.RESOLVED)markBlocked(node,edge?.state??ReferenceState.INVALID,edge?.diagnostics??[]);}
for(const object of Object.values(store?.project?.scene?.objects??{})){if(object?.type!=='feature.revolve')continue;const node=nodes.get(object.objectId),refs=[[object.data?.sourceProfileRef,'PROFILE_TO_REVOLVE'],[object.data?.axisRef,'AXIS_TO_REVOLVE']];if(refs.some(([ref])=>!ref)){node.state=DependencyNodeState.MISSING;node.diagnostics.push({code:'SOURCE_REFERENCE_MISSING',message:'Revolve benötigt PROFILE- und AXIS-Referenz.'});continue;}for(const[ref,kind]of refs){const resolution=resolveStableReference(store,ref),edge=createDependencyEdge(store,object.objectId,ref,kind);if(edge)addEdge(outgoing,incoming,edge);if(resolution.state!==ReferenceState.RESOLVED)markBlocked(node,resolution.state,resolution.diagnostics);}}
for(const dependency of declaredDependencies??[]){const dependentObjectId=dependency?.dependentObjectId,node=nodes.get(dependentObjectId),edge=createDependencyEdge(store,dependentObjectId,dependency?.reference,dependency?.kind);if(!node||!edge)continue;addEdge(outgoing,incoming,edge);if(edge.state!==ReferenceState.RESOLVED)markBlocked(node,edge.state,edge.diagnostics);}
for(const edges of outgoing.values())edges.sort((a,b)=>a.dependentObjectId.localeCompare(b.dependentObjectId));for(const edges of incoming.values())edges.sort((a,b)=>a.sourceObjectId.localeCompare(b.sourceObjectId));const allEdges=[...outgoing.values()].flat(),cycleEdges=allEdges.map(edge=>edge.kind==='PLANE_REFERENCE_TO_DERIVED_WORK_PLANE'&&edge.state===ReferenceState.BLOCKED&&store?.getObject?.(edge.sourceObjectId)?{...edge,state:ReferenceState.RESOLVED}:edge),cycles=detectDependencyCycles(cycleEdges);for(const cycle of cycles)for(const objectId of cycle){const node=nodes.get(objectId);if(!node)continue;node.state=DependencyNodeState.BLOCKED;node.upstreamState='CYCLE';node.diagnostics.push({code:'DEPENDENCY_CYCLE',message:`Dependency-Zyklus erkannt: ${cycle.join(' → ')}.`});}const projectEdge=edge=>({...edge,reference:cloneRef(edge.reference),diagnostics:(edge.diagnostics??[]).map(cloneDiagnostic)});return{nodes,outgoing,incoming,cycles:cycles.map(c=>[...c]),hasCycles:cycles.length>0,dependentsOf(id){return(outgoing.get(id)??[]).map(projectEdge);},dependenciesOf(id){return(incoming.get(id)??[]).map(projectEdge);},nodeState(id){const node=nodes.get(id);return node?{...node,diagnostics:node.diagnostics.map(cloneDiagnostic)}:null;}};}
export function visitDependents(store,sourceObjectId,visitor,declaredDependencies=[]){const graph=buildDependencyGraph(store,declaredDependencies),changed=[];for(const edge of graph.dependentsOf(sourceObjectId)){if(edge.state!==ReferenceState.RESOLVED)continue;if(graph.nodeState(edge.dependentObjectId)?.state===DependencyNodeState.BLOCKED)continue;const dependent=store?.getObject?.(edge.dependentObjectId)??null;if(!dependent)continue;visitor(dependent,edge,graph);changed.push(dependent.objectId);}return changed;}
export function enforceBlockedDependencyState(store,declaredDependencies=[]){const graph=buildDependencyGraph(store,declaredDependencies),blocked=[];for(const[objectId,node]of graph.nodes){if(node.state!==DependencyNodeState.BLOCKED)continue;const object=store?.getObject?.(objectId)??null;if(!['feature.extrude','feature.thin-extrude','feature.revolve'].includes(object?.type))continue;object.data??={};object.extensions??={};if(object.type==='feature.thin-extrude')object.data.contour=[];else if(object.type==='feature.revolve'){object.data.profile=null;object.data.revolveProfile=[];object.data.axis=null;}else if(Array.isArray(object.data.sourceProfileRefs)&&object.data.sourceProfileRefs.length)object.data.profiles=[];else object.data.profile=null;object.extensions.recomputeState={state:DependencyNodeState.BLOCKED,upstreamState:node.upstreamState,diagnostics:node.diagnostics.map(cloneDiagnostic)};blocked.push(objectId);}return blocked;}
