import { recognizeProfileIdentity } from '../model/sketch-profile-path-identity.js';
import { resolveSketchPlaneBinding } from './sketch-plane-binding.js';
import { ReferenceState,ReferenceTargetKind,createReferenceResolution,resolveStableReference } from './stable-reference.js';
const EPS=1e-9,add=(a,b)=>({x:a.x+b.x,y:a.y+b.y,z:a.z+b.z}),scale=(v,s)=>({x:v.x*s,y:v.y*s,z:v.z*s}),cross=(a,b)=>({x:a.y*b.z-a.z*b.y,y:a.z*b.x-a.x*b.z,z:a.x*b.y-a.y*b.x}),len=v=>Math.hypot(v.x,v.y,v.z),norm=v=>{const l=len(v);return l>EPS?scale(v,1/l):null;};
const rotate=(v,q={x:0,y:0,z:0,w:1})=>{const x=q.x??0,y=q.y??0,z=q.z??0,w=q.w??1,ix=w*v.x+y*v.z-z*v.y,iy=w*v.y+z*v.x-x*v.z,iz=w*v.z+x*v.y-y*v.x,iw=-x*v.x-y*v.y-z*v.z;return{x:ix*w+iw*-x+iy*-z-iz*-y,y:iy*w+iw*-y+iz*-x-ix*-z,z:iz*w+iw*-z+ix*-y-iy*-x};};
function frame(store,s){const b=resolveSketchPlaneBinding(store,s);if(b.frame)return{origin:{...b.frame.origin},xAxis:{...b.frame.xAxis},yAxis:{...b.frame.yAxis},normal:norm(cross(b.frame.xAxis,b.frame.yAxis))};const t=s.transform??{},sc=t.scale??{x:1,y:1,z:1};const x=norm(rotate({x:sc.x??1,y:0,z:0},t.rotation)),y=norm(rotate({x:0,y:sc.y??1,z:0},t.rotation));return{origin:{x:Number(t.position?.x??0),y:Number(t.position?.y??0),z:Number(t.position?.z??0)},xAxis:x,yAxis:y,normal:norm(cross(x,y))};}
const world=(f,p)=>add(f.origin,add(scale(f.xAxis,Number(p.x)),scale(f.yAxis,Number(p.y))));
const clear=o=>{o.data.sections=[];};
const fail=(o,ref,state,code,message)=>{clear(o);o.extensions??={};o.extensions.recomputeState={state:state===ReferenceState.INVALID?ReferenceState.INVALID:ReferenceState.BLOCKED,upstreamState:state,diagnostics:[{code,message}]};return createReferenceResolution(ref,state,[{code,message}]);};
export function syncLoftSourceReferences(store,o){if(o?.type!=='feature.loft')return null;o.data??={};o.extensions??={};const refs=o.data.sourceProfileRefs;if(!Array.isArray(refs)||refs.length<2)return fail(o,refs?.[0]??null,ReferenceState.INVALID,'LOFT_REQUIRES_MULTIPLE_PROFILES','Loft benötigt mindestens zwei geordnete PROFILE-Referenzen.');const sections=[];for(let index=0;index<refs.length;index++){const ref=refs[index];if(ref?.targetKind!==ReferenceTargetKind.PROFILE)return fail(o,ref,ReferenceState.INVALID,'PROFILE_REFERENCE_REQUIRED','Loft akzeptiert ausschließlich PROFILE-Referenzen.');const resolution=resolveStableReference(store,ref);if(resolution.state!==ReferenceState.RESOLVED)return fail(o,ref,resolution.state,`UPSTREAM_${resolution.state}`,`Loft-Section ${index} ist ${resolution.state}.`);const sketch=store.getObject?.(ref.ownerId),identity=sketch?.data?.profileIdentities?.[ref.targetId],recognized=recognizeProfileIdentity(sketch,identity);if(recognized.state!==ReferenceState.RESOLVED||!recognized.target)return fail(o,ref,recognized.state,`PROFILE_${recognized.state}`,`Loft-Profil ${index} ist ${recognized.state}.`);if((recognized.target.holes??[]).length)return fail(o,ref,ReferenceState.INVALID,'LOFT_PROFILE_HOLES_OUT_OF_SCOPE','WD-23E Foundation unterstützt Profile ohne Innenkonturen.');const points=recognized.target.outerContour?.points??recognized.target.points??[];if(points.length<3)return fail(o,ref,ReferenceState.INVALID,'INVALID_LOFT_PROFILE','Loft-Profil benötigt mindestens drei Ringpunkte.');const f=frame(store,sketch);if(!f.xAxis||!f.yAxis||!f.normal)return fail(o,ref,ReferenceState.INVALID,'INVALID_LOFT_PLANE','Loft-Profil besitzt keine gültige räumliche Ebene.');sections.push({sourceRef:structuredClone(ref),profileKey:recognized.target.profileKey??null,points:points.map(p=>world(f,p))});}const count=sections[0].points.length;if(sections.some(s=>s.points.length!==count))return fail(o,refs[0],ReferenceState.INVALID,'INCOMPATIBLE_LOFT_RING_TOPOLOGY','WD-23E Foundation verlangt gleiche deterministische Ringpunktanzahl je Section.');o.data.sections=sections;o.extensions.recomputeState={state:'READY',upstreamState:null,diagnostics:[]};return createReferenceResolution(refs[0],ReferenceState.RESOLVED,[]);}
export function syncAllLoftSourceReferences(store){const out=[];for(const o of Object.values(store?.project?.scene?.objects??{}))if(o?.type==='feature.loft')out.push({objectId:o.objectId,resolution:syncLoftSourceReferences(store,o)});return out;}
