import * as THREE from 'three';
import { createAssemblyObject, createBoxObject, createCylinderObject, createGroupObject, createProject, createSphereObject, validateProject } from '../model/project.js';

export class AppStore {
  constructor(){this.project=createProject();this.selection={selectedObjectIds:[],activeObjectId:null,hoveredObjectId:null};this.toolMode='translate';this.listeners=new Set();this.undoStack=[];this.redoStack=[];this.historyLimit=100;}
  subscribe(listener){this.listeners.add(listener);return()=>this.listeners.delete(listener);} emit(type,payload={}){const event={type,...payload};for(const listener of this.listeners)listener(event,this);}
  snapshot(){return structuredClone(this.project);} restore(snapshot,eventType='projectChanged'){this.project=structuredClone(snapshot);this.clearSelection(false);this.emit(eventType);this.emit('historyChanged');}
  pushHistory(before,label){this.undoStack.push({before,after:this.snapshot(),label});if(this.undoStack.length>this.historyLimit)this.undoStack.shift();this.redoStack=[];this.emit('historyChanged');}
  newProject(){this.project=createProject();this.clearSelection(false);this.undoStack=[];this.redoStack=[];this.emit('projectChanged');this.emit('historyChanged');}
  replaceProject(project){const result=validateProject(project);if(!result.valid)throw new Error(result.errors.join('\n'));this.project=structuredClone(project);this.clearSelection(false);this.undoStack=[];this.redoStack=[];this.emit('projectLoaded');this.emit('historyChanged');}
  getObject(id){return this.project.scene.objects[id]??null;}

  addObject(factory,label){const before=this.snapshot(),o=factory(this.project);this.project.scene.objects[o.objectId]=o;this.project.scene.rootObjectIds.push(o.objectId);this.touch();this.select(o.objectId,false);this.pushHistory(before,label);this.emit('objectCreated',{objectId:o.objectId});return o.objectId;}
  addBox(){return this.addObject(createBoxObject,'Würfel erzeugen');} addSphere(){return this.addObject(createSphereObject,'Kugel erzeugen');} addCylinder(){return this.addObject(createCylinderObject,'Zylinder erzeugen');}

  select(objectId,notify=true,additive=false){if(objectId&&!this.getObject(objectId))return;if(!objectId){this.clearSelection(notify);return;}if(additive){const set=new Set(this.selection.selectedObjectIds);set.has(objectId)?set.delete(objectId):set.add(objectId);this.selection.selectedObjectIds=[...set];this.selection.activeObjectId=set.has(objectId)?objectId:(this.selection.selectedObjectIds.at(-1)??null);}else{this.selection.selectedObjectIds=[objectId];this.selection.activeObjectId=objectId;}if(notify)this.emit('selectionChanged');}
  clearSelection(notify=true){this.selection.selectedObjectIds=[];this.selection.activeObjectId=null;this.selection.hoveredObjectId=null;if(notify)this.emit('selectionChanged');}
  setToolMode(mode){if(!['translate','rotate','scale'].includes(mode))return;this.toolMode=mode;this.emit('toolChanged',{mode});}

  setName(id,name){const o=this.getObject(id);if(!o)return;const next=String(name||'Objekt');if(next===o.name)return;const before=this.snapshot();o.name=next;this.touch();this.pushHistory(before,'Objekt umbenennen');this.emit('objectChanged',{objectId:id});}
  setTransformFromEuler(id,next,options={}){const o=this.getObject(id);if(!o)return;const before=options.beforeSnapshot??this.snapshot();const px=finite(next.position?.x,o.transform.position.x),py=finite(next.position?.y,o.transform.position.y),pz=finite(next.position?.z,o.transform.position.z);const sx=nonZero(next.scale?.x,o.transform.scale.x),sy=nonZero(next.scale?.y,o.transform.scale.y),sz=nonZero(next.scale?.z,o.transform.scale.z);let q;if(next.quaternion)q=new THREE.Quaternion(next.quaternion.x,next.quaternion.y,next.quaternion.z,next.quaternion.w).normalize();else{const e=new THREE.Euler(THREE.MathUtils.degToRad(finite(next.rotationDeg?.x,0)),THREE.MathUtils.degToRad(finite(next.rotationDeg?.y,0)),THREE.MathUtils.degToRad(finite(next.rotationDeg?.z,0)),'XYZ');q=new THREE.Quaternion().setFromEuler(e).normalize();}o.transform.position={x:px,y:py,z:pz};o.transform.rotation={x:q.x,y:q.y,z:q.z,w:q.w};o.transform.scale={x:sx,y:sy,z:sz};this.touch();if(options.recordHistory!==false)this.pushHistory(before,options.label??'Transform ändern');this.emit('objectChanged',{objectId:id});}
  setPivot(id,next){const o=this.getObject(id);if(!o)return;const before=this.snapshot();o.transform.pivot={x:finite(next.x,o.transform.pivot.x),y:finite(next.y,o.transform.pivot.y),z:finite(next.z,o.transform.pivot.z)};this.touch();this.pushHistory(before,'Pivot ändern');this.emit('geometryChanged',{objectId:id});}
  setGeometry(id,next){const o=this.getObject(id);if(!o||!o.type.startsWith('primitive.'))return;const before=this.snapshot();if(o.type==='primitive.box')o.data.size={x:positive(next.x,o.data.size.x),y:positive(next.y,o.data.size.y),z:positive(next.z,o.data.size.z)};if(o.type==='primitive.sphere')o.data.radius=positive(next.radius,o.data.radius);if(o.type==='primitive.cylinder'){o.data.radius=positive(next.radius,o.data.radius);o.data.height=positive(next.height,o.data.height);}this.touch();this.pushHistory(before,'Abmessungen ändern');this.emit('geometryChanged',{objectId:id});}

  createContainer(type){const ids=this.selection.selectedObjectIds.filter(id=>this.getObject(id)?.parentId===null);if(!ids.length)return null;const before=this.snapshot(),container=(type==='assembly'?createAssemblyObject:createGroupObject)(this.project);this.project.scene.objects[container.objectId]=container;this.project.scene.rootObjectIds=this.project.scene.rootObjectIds.filter(id=>!ids.includes(id));this.project.scene.rootObjectIds.push(container.objectId);ids.forEach((id,i)=>{const o=this.getObject(id);o.parentId=container.objectId;o.order=i;});this.touch();this.selection.selectedObjectIds=[container.objectId];this.selection.activeObjectId=container.objectId;this.pushHistory(before,type==='assembly'?'Baugruppe bilden':'Gruppe bilden');this.emit('projectChanged');this.emit('selectionChanged');return container.objectId;}
  groupSelected(){return this.createContainer('group');} assemblySelected(){return this.createContainer('assembly');}

  deleteSelected(){const ids=[...this.selection.selectedObjectIds];if(!ids.length)return false;const before=this.snapshot();const remove=new Set(ids);let changed=true;while(changed){changed=false;for(const o of Object.values(this.project.scene.objects))if(o.parentId&&remove.has(o.parentId)&&!remove.has(o.objectId)){remove.add(o.objectId);changed=true;}}for(const id of remove)delete this.project.scene.objects[id];this.project.scene.rootObjectIds=this.project.scene.rootObjectIds.filter(id=>!remove.has(id));this.clearSelection(false);this.touch();this.pushHistory(before,'Objekt löschen');this.emit('projectChanged');return true;}
  duplicateSelected(){const id=this.selection.activeObjectId,source=this.getObject(id);if(!source)return null;const before=this.snapshot(),copy=structuredClone(source);copy.objectId=`obj_${crypto.randomUUID()}`;copy.parentId=null;copy.name=`${source.name} Kopie`;copy.order=this.project.scene.rootObjectIds.length;copy.transform.position.x+=0.25;copy.transform.position.z+=0.25;this.project.scene.objects[copy.objectId]=copy;this.project.scene.rootObjectIds.push(copy.objectId);this.touch();this.select(copy.objectId,false);this.pushHistory(before,'Objekt duplizieren');this.emit('projectChanged');this.emit('selectionChanged');return copy.objectId;}
  undo(){const e=this.undoStack.pop();if(!e)return false;this.redoStack.push(e);this.project=structuredClone(e.before);this.clearSelection(false);this.emit('projectChanged');this.emit('historyChanged');return true;} redo(){const e=this.redoStack.pop();if(!e)return false;this.undoStack.push(e);this.project=structuredClone(e.after);this.clearSelection(false);this.emit('projectChanged');this.emit('historyChanged');return true;}
  touch(){this.project.project.modifiedAt=new Date().toISOString();}
}
function finite(value,fallback){const n=Number(value);return Number.isFinite(n)?n:fallback;} function nonZero(value,fallback){const n=finite(value,fallback);return n===0?fallback:n;} function positive(value,fallback){const n=finite(value,fallback);return n>0?n:fallback;}
