import * as THREE from 'three';
import { createAssemblyObject, createBoxObject, createCylinderObject, createGroupObject, createProject, createSphereObject, validateProject } from '../model/project.js';

export class AppStore {
  constructor(){this.project=createProject();this.selection={selectedObjectIds:[],activeObjectId:null,hoveredObjectId:null};this.toolMode='translate';this.coordinateSpace='world';this.snap={enabled:false,translate:0.1,rotateDeg:15,scale:0.1};this.listeners=new Set();this.undoStack=[];this.redoStack=[];this.historyLimit=100;}
  subscribe(fn){this.listeners.add(fn);return()=>this.listeners.delete(fn);} emit(type,payload={}){for(const fn of this.listeners)fn({type,...payload},this);} snapshot(){return structuredClone(this.project);}
  pushHistory(before,label){this.undoStack.push({before,after:this.snapshot(),label});if(this.undoStack.length>this.historyLimit)this.undoStack.shift();this.redoStack=[];this.emit('historyChanged');}
  newProject(){this.project=createProject();this.clearSelection(false);this.undoStack=[];this.redoStack=[];this.emit('projectChanged');this.emit('historyChanged');}
  replaceProject(project){const r=validateProject(project);if(!r.valid)throw new Error(r.errors.join('\n'));this.project=structuredClone(project);this.clearSelection(false);this.undoStack=[];this.redoStack=[];this.emit('projectLoaded');this.emit('historyChanged');}
  getObject(id){return this.project.scene.objects[id]??null;}
  addObject(factory,label){const before=this.snapshot(),o=factory(this.project);this.project.scene.objects[o.objectId]=o;this.project.scene.rootObjectIds.push(o.objectId);this.touch();this.select(o.objectId,false);this.pushHistory(before,label);this.emit('objectCreated',{objectId:o.objectId});return o.objectId;}
  addBox(){return this.addObject(createBoxObject,'Würfel erzeugen');} addSphere(){return this.addObject(createSphereObject,'Kugel erzeugen');} addCylinder(){return this.addObject(createCylinderObject,'Zylinder erzeugen');}
  select(id,notify=true,additive=false){if(id&&!this.getObject(id))return;if(!id){this.clearSelection(notify);return;}if(additive){const s=new Set(this.selection.selectedObjectIds);s.has(id)?s.delete(id):s.add(id);this.selection.selectedObjectIds=[...s];this.selection.activeObjectId=s.has(id)?id:(this.selection.selectedObjectIds.at(-1)??null);}else{this.selection.selectedObjectIds=[id];this.selection.activeObjectId=id;}if(notify)this.emit('selectionChanged');}
  clearSelection(notify=true){this.selection.selectedObjectIds=[];this.selection.activeObjectId=null;this.selection.hoveredObjectId=null;if(notify)this.emit('selectionChanged');}
  setToolMode(mode){if(!['translate','rotate','scale'].includes(mode))return;this.toolMode=mode;this.emit('toolChanged',{mode});}
  setCoordinateSpace(space){if(!['world','local'].includes(space))return;this.coordinateSpace=space;this.emit('spaceChanged',{space});}
  setSnapEnabled(enabled){this.snap.enabled=!!enabled;this.emit('snapChanged');}
  setSnapValues(next){this.snap.translate=positive(next.translate,this.snap.translate);this.snap.rotateDeg=positive(next.rotateDeg,this.snap.rotateDeg);this.snap.scale=positive(next.scale,this.snap.scale);this.emit('snapChanged');}
  setName(id,name){const o=this.getObject(id);if(!o)return;const n=String(name||'Objekt');if(n===o.name)return;const before=this.snapshot();o.name=n;this.touch();this.pushHistory(before,'Objekt umbenennen');this.emit('objectChanged',{objectId:id});}
  setTransformFromEuler(id,next,options={}){const o=this.getObject(id);if(!o)return;const before=options.beforeSnapshot??this.snapshot();const p={x:finite(next.position?.x,o.transform.position.x),y:finite(next.position?.y,o.transform.position.y),z:finite(next.position?.z,o.transform.position.z)};const s={x:nonZero(next.scale?.x,o.transform.scale.x),y:nonZero(next.scale?.y,o.transform.scale.y),z:nonZero(next.scale?.z,o.transform.scale.z)};const e=new THREE.Euler(THREE.MathUtils.degToRad(finite(next.rotationDeg?.x,0)),THREE.MathUtils.degToRad(finite(next.rotationDeg?.y,0)),THREE.MathUtils.degToRad(finite(next.rotationDeg?.z,0)),'XYZ');const q=new THREE.Quaternion().setFromEuler(e).normalize();o.transform.position=p;o.transform.rotation={x:q.x,y:q.y,z:q.z,w:q.w};o.transform.scale=s;this.touch();if(options.recordHistory!==false)this.pushHistory(before,options.label??'Transform ändern');this.emit('objectChanged',{objectId:id});}
  setWorldTransformFromEuler(id,next){const o=this.getObject(id);if(!o)return;const before=this.snapshot();const current=this.getWorldTransform(id);const p={x:finite(next.position?.x,current.position.x),y:finite(next.position?.y,current.position.y),z:finite(next.position?.z,current.position.z)};const s={x:nonZero(next.scale?.x,current.scale.x),y:nonZero(next.scale?.y,current.scale.y),z:nonZero(next.scale?.z,current.scale.z)};const e=new THREE.Euler(THREE.MathUtils.degToRad(finite(next.rotationDeg?.x,0)),THREE.MathUtils.degToRad(finite(next.rotationDeg?.y,0)),THREE.MathUtils.degToRad(finite(next.rotationDeg?.z,0)),'XYZ');const q=new THREE.Quaternion().setFromEuler(e);const world=new THREE.Matrix4().compose(new THREE.Vector3(p.x,p.y,p.z),q,new THREE.Vector3(s.x,s.y,s.z));this.applyWorldMatrixAsLocal(id,world);this.touch();this.pushHistory(before,'Welttransform ändern');this.emit('projectChanged');}
  setPivot(id,next){const o=this.getObject(id);if(!o)return;const before=this.snapshot();o.transform.pivot={x:finite(next.x,o.transform.pivot.x),y:finite(next.y,o.transform.pivot.y),z:finite(next.z,o.transform.pivot.z)};this.touch();this.pushHistory(before,'Pivot ändern');this.emit('geometryChanged',{objectId:id});}
  setPivotPreset(id,preset){const o=this.getObject(id);if(!o)return;let p={x:0,y:0,z:0};if(preset==='bottom'){if(o.type==='primitive.box')p={x:0,y:-o.data.size.y/2,z:0};else if(o.type==='primitive.sphere')p={x:0,y:-o.data.radius,z:0};else if(o.type==='primitive.cylinder')p={x:0,y:-o.data.height/2,z:0};}this.setPivot(id,p);}
  setGeometry(id,next){const o=this.getObject(id);if(!o||!o.type.startsWith('primitive.'))return;const before=this.snapshot();if(o.type==='primitive.box')o.data.size={x:positive(next.x,o.data.size.x),y:positive(next.y,o.data.size.y),z:positive(next.z,o.data.size.z)};if(o.type==='primitive.sphere')o.data.radius=positive(next.radius,o.data.radius);if(o.type==='primitive.cylinder'){o.data.radius=positive(next.radius,o.data.radius);o.data.height=positive(next.height,o.data.height);}this.touch();this.pushHistory(before,'Abmessungen ändern');this.emit('geometryChanged',{objectId:id});}
  createContainer(type){const ids=this.selection.selectedObjectIds.filter(id=>this.getObject(id)?.parentId===null);if(!ids.length)return null;const before=this.snapshot(),c=(type==='assembly'?createAssemblyObject:createGroupObject)(this.project);this.project.scene.objects[c.objectId]=c;this.project.scene.rootObjectIds=this.project.scene.rootObjectIds.filter(id=>!ids.includes(id));this.project.scene.rootObjectIds.push(c.objectId);ids.forEach((id,i)=>{this.getObject(id).parentId=c.objectId;this.getObject(id).order=i;});this.touch();this.selection.selectedObjectIds=[c.objectId];this.selection.activeObjectId=c.objectId;this.pushHistory(before,type==='assembly'?'Baugruppe bilden':'Gruppe bilden');this.emit('projectChanged');this.emit('selectionChanged');return c.objectId;}
  groupSelected(){return this.createContainer('group');} assemblySelected(){return this.createContainer('assembly');}
  ungroupSelected(){const id=this.selection.activeObjectId,c=this.getObject(id);if(!c||!['group','assembly'].includes(c.type))return false;const before=this.snapshot(),children=Object.values(this.project.scene.objects).filter(o=>o.parentId===id);for(const child of children)this.reparent(child.objectId,c.parentId,false);delete this.project.scene.objects[id];this.project.scene.rootObjectIds=this.project.scene.rootObjectIds.filter(x=>x!==id);if(c.parentId===null)for(const child of children)if(!this.project.scene.rootObjectIds.includes(child.objectId))this.project.scene.rootObjectIds.push(child.objectId);this.clearSelection(false);this.touch();this.pushHistory(before,c.type==='assembly'?'Baugruppe auflösen':'Gruppe auflösen');this.emit('projectChanged');return true;}
  canReparent(id,parentId){if(!this.getObject(id)||id===parentId)return false;if(parentId!==null&&!this.getObject(parentId))return false;let p=parentId;while(p){if(p===id)return false;p=this.getObject(p)?.parentId??null;}return true;}
  reparent(id,parentId,record=true){if(!this.canReparent(id,parentId))return false;const before=record?this.snapshot():null,world=this.worldMatrix(id),o=this.getObject(id),oldParent=o.parentId;o.parentId=parentId;this.project.scene.rootObjectIds=this.project.scene.rootObjectIds.filter(x=>x!==id);if(parentId===null)this.project.scene.rootObjectIds.push(id);o.order=parentId===null?this.project.scene.rootObjectIds.length-1:Object.values(this.project.scene.objects).filter(x=>x.parentId===parentId&&x.objectId!==id).length;this.applyWorldMatrixAsLocal(id,world);this.touch();if(record)this.pushHistory(before,'Reparenting');this.emit('projectChanged');return oldParent!==parentId;}
  worldMatrix(id){const o=this.getObject(id);if(!o)return new THREE.Matrix4();const local=matrixFromTransform(o.transform);return o.parentId?this.worldMatrix(o.parentId).multiply(local):local;}
  getWorldTransform(id){const p=new THREE.Vector3(),q=new THREE.Quaternion(),s=new THREE.Vector3();this.worldMatrix(id).decompose(p,q,s);return{position:{x:p.x,y:p.y,z:p.z},rotation:{x:q.x,y:q.y,z:q.z,w:q.w},scale:{x:s.x,y:s.y,z:s.z}};}
  applyWorldMatrixAsLocal(id,world){const o=this.getObject(id);if(!o)return;const local=o.parentId?this.worldMatrix(o.parentId).invert().multiply(world.clone()):world.clone();const p=new THREE.Vector3(),q=new THREE.Quaternion(),s=new THREE.Vector3();local.decompose(p,q,s);o.transform.position={x:p.x,y:p.y,z:p.z};o.transform.rotation={x:q.x,y:q.y,z:q.z,w:q.w};o.transform.scale={x:s.x,y:s.y,z:s.z};}
  deleteSelected(){const ids=[...this.selection.selectedObjectIds];if(!ids.length)return false;const before=this.snapshot(),remove=new Set(ids);let changed=true;while(changed){changed=false;for(const o of Object.values(this.project.scene.objects))if(o.parentId&&remove.has(o.parentId)&&!remove.has(o.objectId)){remove.add(o.objectId);changed=true;}}for(const id of remove)delete this.project.scene.objects[id];this.project.scene.rootObjectIds=this.project.scene.rootObjectIds.filter(id=>!remove.has(id));this.clearSelection(false);this.touch();this.pushHistory(before,'Objekt löschen');this.emit('projectChanged');return true;}
  duplicateSelected(){
    const id=this.selection.activeObjectId,source=this.getObject(id);if(!source)return null;
    const before=this.snapshot(),idMap=new Map(),originals=this.project.scene.objects;
    const collect=(sourceId)=>{
      const original=originals[sourceId];if(!original)return null;
      const copy=structuredClone(original),newId=`obj_${crypto.randomUUID()}`;
      idMap.set(sourceId,newId);copy.objectId=newId;copy.name=`${original.name} Kopie`;
      this.project.scene.objects[newId]=copy;
      const children=Object.values(originals).filter(o=>o.parentId===sourceId).sort((a,b)=>a.order-b.order);
      for(const child of children)collect(child.objectId);
      return newId;
    };
    const rootCopyId=collect(id);
    for(const [oldId,newId] of idMap){
      const original=originals[oldId],copy=this.project.scene.objects[newId];
      copy.parentId=original.parentId&&idMap.has(original.parentId)?idMap.get(original.parentId):null;
      copy.order=original.order;
    }
    const rootCopy=this.project.scene.objects[rootCopyId];rootCopy.parentId=null;rootCopy.order=this.project.scene.rootObjectIds.length;rootCopy.transform.position.x+=0.25;rootCopy.transform.position.z+=0.25;
    this.project.scene.rootObjectIds.push(rootCopyId);
    this.touch();this.select(rootCopyId,false);this.pushHistory(before,['group','assembly'].includes(source.type)?'Unterbaum duplizieren':'Objekt duplizieren');this.emit('projectChanged');this.emit('selectionChanged');return rootCopyId;
  }
  undo(){const e=this.undoStack.pop();if(!e)return false;this.redoStack.push(e);this.project=structuredClone(e.before);this.clearSelection(false);this.emit('projectChanged');this.emit('historyChanged');return true;} redo(){const e=this.redoStack.pop();if(!e)return false;this.undoStack.push(e);this.project=structuredClone(e.after);this.clearSelection(false);this.emit('projectChanged');this.emit('historyChanged');return true;} touch(){this.project.project.modifiedAt=new Date().toISOString();}
}
function matrixFromTransform(t){return new THREE.Matrix4().compose(new THREE.Vector3(t.position.x,t.position.y,t.position.z),new THREE.Quaternion(t.rotation.x,t.rotation.y,t.rotation.z,t.rotation.w),new THREE.Vector3(t.scale.x,t.scale.y,t.scale.z));}
function finite(v,f){const n=Number(v);return Number.isFinite(n)?n:f;}function nonZero(v,f){const n=finite(v,f);return n===0?f:n;}function positive(v,f){const n=finite(v,f);return n>0?n:f;}
