import { recognizeProfileIdentity, recognizePathIdentity } from '../model/sketch-profile-path-identity.js';
import { resolveSketchPlaneBinding } from './sketch-plane-binding.js';
import { ReferenceState, ReferenceTargetKind, createReferenceResolution, resolveStableReference } from './stable-reference.js';

const EPS=1e-9,add=(a,b)=>({x:a.x+b.x,y:a.y+b.y,z:a.z+b.z}),sub=(a,b)=>({x:a.x-b.x,y:a.y-b.y,z:a.z-b.z}),scale=(v,s)=>({x:v.x*s,y:v.y*s,z:v.z*s}),dot=(a,b)=>a.x*b.x+a.y*b.y+a.z*b.z,cross=(a,b)=>({x:a.y*b.z-a.z*b.y,y:a.z*b.x-a.x*b.z,z:a.x*b.y-a.y*b.x}),length=v=>Math.hypot(v.x,v.y,v.z),normalize=v=>{const l=length(v);return l>EPS?scale(v,1/l):null;};
const rotateQuaternion=(v,q={x:0,y:0,z:0,w:1})=>{const x=q.x??0,y=q.y??0,z=q.z??0,w=q.w??1,ix=w*v.x+y*v.z-z*v.y,iy=w*v.y+z*v.x-x*v.z,iz=w*v.z+x*v.y-y*v.x,iw=-x*v.x-y*v.y-z*v.z;return{x:ix*w+iw*-x+iy*-z-iz*-y,y:iy*w+iw*-y+iz*-x-ix*-z,z:iz*w+iw*-z+ix*-y-iy*-x};};
function sketchFrame(store,sketch){const binding=resolveSketchPlaneBinding(store,sketch);if(binding.frame)return{origin:{...binding.frame.origin},xAxis:{...binding.frame.xAxis},yAxis:{...binding.frame.yAxis},normal:normalize(cross(binding.frame.xAxis,binding.frame.yAxis))};const t=sketch.transform??{},s=t.scale??{x:1,y:1,z:1},origin=t.position??{x:0,y:0,z:0},xAxis=normalize(rotateQuaternion({x:s.x??1,y:0,z:0},t.rotation)),yAxis=normalize(rotateQuaternion({x:0,y:s.y??1,z:0},t.rotation));return{origin:{x:Number(origin.x??0),y:Number(origin.y??0),z:Number(origin.z??0)},xAxis,yAxis,normal:normalize(cross(xAxis,yAxis))};}
const toWorld=(f,p)=>add(f.origin,add(scale(f.xAxis,Number(p.x)),scale(f.yAxis,Number(p.y)))),clone2=points=>(points??[]).map(p=>({x:Number(p.x),y:Number(p.y)})),profileCache=p=>({profileKey:p?.profileKey??null,points:clone2(p?.outerContour?.points??p?.points),holes:(p?.holes??[]).map(h=>({points:clone2(h?.points)}))});
function worldPath(store,sketch,path){const frame=sketchFrame(store,sketch);if(!frame.xAxis||!frame.yAxis||!frame.normal)return null;const points=[];for(const curve of path?.curves??[])for(let i=0;i<(curve.tessellation??[]).length;i++){const p=toWorld(frame,curve.tessellation[i]),last=points.at(-1);if(last&&i===0&&length(sub(last,p))<=EPS)continue;points.push(p);}return points.length>=2?{points,frame}:null;}
function tangents(points){return points.map((p,i)=>normalize(sub(points[Math.min(points.length-1,i+1)],points[Math.max(0,i-1)])));}
function transportNormal(n,a,b){const axis=cross(a,b),sin=length(axis),cos=Math.max(-1,Math.min(1,dot(a,b)));if(sin<=EPS)return cos>=0?n:scale(n,-1);const u=scale(axis,1/sin);return add(add(scale(n,cos),scale(cross(u,n),sin)),scale(u,dot(u,n)*(1-cos)));}
export function deriveSweepFrames(points,preferredNormal){if(!Array.isArray(points)||points.length<2)return null;const ts=tangents(points);if(ts.some(t=>!t))return null;let n=normalize(sub(preferredNormal,scale(ts[0],dot(preferredNormal,ts[0]))));if(!n){const f=Math.abs(ts[0].z)<0.9?{x:0,y:0,z:1}:{x:0,y:1,z:0};n=normalize(sub(f,scale(ts[0],dot(f,ts[0]))));}if(!n)return null;const frames=[];for(let i=0;i<points.length;i++){if(i){const transported=transportNormal(n,ts[i-1],ts[i]);n=normalize(sub(transported,scale(ts[i],dot(transported,ts[i]))));}if(!n)return null;const b=normalize(cross(ts[i],n));if(!b)return null;n=normalize(cross(b,ts[i]));frames.push({origin:{...points[i]},tangent:{...ts[i]},normal:{...n},binormal:{...b}});}return frames;}
const clear=o=>{o.data.profile=null;o.data.pathPoints=[];o.data.frames=[];};
const blocked=(o,r,m)=>{clear(o);o.extensions??={};o.extensions.recomputeState={state:ReferenceState.BLOCKED,upstreamState:r?.state??ReferenceState.INVALID,diagnostics:[{code:`UPSTREAM_${r?.state??ReferenceState.INVALID}`,message:m},...(r?.diagnostics??[])]};};
const invalid=(o,ref,code,message)=>{const r=createReferenceResolution(ref,ReferenceState.INVALID,[{code,message}]);clear(o);o.extensions??={};o.extensions.recomputeState={state:ReferenceState.INVALID,upstreamState:null,diagnostics:r.diagnostics};return r;};
export function syncSweepSourceReferences(store,o){if(o?.type!=='feature.sweep')return null;o.data??={};o.extensions??={};const pr=o.data.sourceProfileRef,rr=o.data.sourcePathRef;if(pr?.targetKind!==ReferenceTargetKind.PROFILE)return invalid(o,pr??rr,'PROFILE_REFERENCE_REQUIRED','Sweep benötigt genau eine stabile PROFILE-Referenz.');if(rr?.targetKind!==ReferenceTargetKind.PATH)return invalid(o,rr??pr,'PATH_REFERENCE_REQUIRED','Sweep benötigt genau eine stabile PATH-Referenz.');const prs=resolveStableReference(store,pr);if(prs.state!==ReferenceState.RESOLVED){blocked(o,prs,`Sweep ist blockiert, weil die Profilreferenz ${prs.state} ist.`);return prs;}const rrs=resolveStableReference(store,rr);if(rrs.state!==ReferenceState.RESOLVED){blocked(o,rrs,`Sweep ist blockiert, weil die Pfadreferenz ${rrs.state} ist.`);return rrs;}const ps=store.getObject?.(pr.ownerId),p=recognizeProfileIdentity(ps,ps?.data?.profileIdentities?.[pr.targetId]);if(p.state!==ReferenceState.RESOLVED||!p.target){const f=createReferenceResolution(pr,p.state,p.diagnostics??[]);blocked(o,f,`Sweep ist blockiert, weil das Profil ${p.state} ist.`);return f;}const rs=store.getObject?.(rr.ownerId),r=recognizePathIdentity(rs,rs?.data?.pathIdentities?.[rr.targetId]);if(r.state!==ReferenceState.RESOLVED||!r.target){const f=createReferenceResolution(rr,r.state,r.diagnostics??[]);blocked(o,f,`Sweep ist blockiert, weil der Pfad ${r.state} ist.`);return f;}if((p.target?.holes??[]).length)return invalid(o,pr,'SWEEP_PROFILE_HOLES_OUT_OF_SCOPE','WD-23D Foundation unterstützt zunächst Profile ohne Innenkonturen.');const wp=worldPath(store,rs,r.target);if(!wp)return invalid(o,rr,'DEGENERATE_SWEEP_PATH','Sweep-Pfad besitzt keine gültige räumliche Länge.');const pf=sketchFrame(store,ps),frames=deriveSweepFrames(wp.points,pf.normal);if(!frames)return invalid(o,rr,'INVALID_SWEEP_FRAME','Reproduzierbarer Sweep-Frame konnte nicht gebildet werden.');o.data.profile=profileCache(p.target);o.data.pathPoints=wp.points.map(x=>({...x}));o.data.frames=frames;o.extensions.recomputeState={state:'READY',upstreamState:null,diagnostics:[]};return createReferenceResolution(pr,ReferenceState.RESOLVED,[]);}
export function syncAllSweepSourceReferences(store){const out=[];for(const o of Object.values(store?.project?.scene?.objects??{}))if(o?.type==='feature.sweep')out.push({objectId:o.objectId,resolution:syncSweepSourceReferences(store,o)});return out;}
