import { AppStore } from './application/store.js';
import { createExtrudeFromSketch, installExtrudeSourceReferenceSync } from './application/extrude.js';
import { installSketchMutationContract } from './application/sketch-mutation.js';
import { installGenericSketchElementMutationContract } from './application/sketch-element-mutation-extension.js';
import { installSketchArcCreationContract } from './application/sketch-arc-creation.js';
import { installSketchSplineCreationContract } from './application/sketch-spline-creation.js';
import { installGenericEndpointConnectivityContract } from './application/sketch-endpoint-connectivity-extension.js';
import { installSketchConnectivityCommands } from './application/sketch-connectivity-commands.js';
import { getSketchElement, getSketchPoint } from './model/sketch-topology.js';
import { ThreeRuntime } from './runtime-three/runtime.js';
import { installExtrudeRuntime } from './runtime-three/extrude.js';
import { installGltfInterchange } from './runtime-three/gltf-interchange.js';
import { installViewportReferenceSystem } from './runtime-three/viewport-reference-system.js';
import { AppUI } from './ui/app.js';
import { installMaterialPanel } from './ui/material-panel.js';
import { installCommandSurface } from './ui/command-surface.js';
import { installGltfPanel } from './ui/gltf-panel.js';
import { installPartialProjectPanel } from './ui/partial-project-panel.js';
import { installSketchEditing } from './ui/sketch-editing.js';
import { installSketchCircleIntegration } from './ui/sketch-circle-integration.js';
import { installSketchArcIntegration } from './ui/sketch-arc-integration.js';
import { installSketchSplineIntegration } from './ui/sketch-spline-integration.js';
import { installSketchMultiSelection } from './ui/sketch-multiselect.js';
import { installSketchConnectivityActions } from './ui/sketch-connectivity-actions.js';
import { installSketchGizmo } from './ui/sketch-gizmo.js';
import { installFeatureOperationsTree } from './ui/feature-operations-tree.js';
import { installFeatureParametersInspector } from './ui/feature-parameters-inspector.js';
import { installObjectVisibility } from './ui/object-visibility.js';
import { installObjectLocking } from './ui/object-locking.js';
import { installObjectTreeScalability } from './ui/object-tree-scalability.js';
import { installProjectLifecycle } from './ui/project-lifecycle.js';
import { installProjectSettings } from './ui/project-settings.js';
import { installCameraObjectPreview } from './ui/camera-object-preview.js';
import { installInspectorDiagnostics } from './ui/inspector-diagnostics.js';

const BUILD_ID = 'WD-21D.2';
const applyBuildIdentity = () => { document.title = `CyberMotion 3D – ${BUILD_ID}`; const buildLabel = document.querySelector('.brand small'); if (buildLabel) buildLabel.textContent = BUILD_ID; };
const store = new AppStore();
const extrudeSourceReferenceSync = installExtrudeSourceReferenceSync(store);
const viewport = document.querySelector('#viewport');
const runtime = new ThreeRuntime(viewport, store);
installExtrudeRuntime(runtime);
const gltfInterchange = installGltfInterchange(runtime, store);
const viewportReferenceSystem = installViewportReferenceSystem(runtime);
const appUI = new AppUI(store);
installMaterialPanel(store);
for (const button of document.querySelectorAll('[data-fixed-view]')) button.addEventListener('click', () => runtime.setFixedView(button.dataset.fixedView));
const sketchPlane=document.querySelector('#sketch-plane'); const newSketchButton=document.querySelector('#new-sketch'); newSketchButton?.addEventListener('click',()=>runtime.createSketchOnPlane(sketchPlane?.value||'front'));
const sketchButtons={line:document.querySelector('#sketch-line'),rectangle:document.querySelector('#sketch-rectangle'),polygon:document.querySelector('#sketch-polygon')};
for(const [mode,button] of Object.entries(sketchButtons))button?.addEventListener('click',()=>{const ok=runtime.toggleSketchInput(mode);if(!ok)alert('Bitte zuerst „Neue Skizze“ anlegen oder eine vorhandene Skizze im Objektbaum auswählen.');});

installSketchMutationContract(store);
installGenericSketchElementMutationContract(store);
installSketchArcCreationContract(store);
installSketchSplineCreationContract(store);
installGenericEndpointConnectivityContract(store);
installSketchConnectivityCommands(store);
installSketchEditing(runtime, store);
installSketchCircleIntegration(runtime, store);
installSketchArcIntegration(runtime, store);
installSketchSplineIntegration(runtime, store);
installSketchMultiSelection(runtime, store);
installSketchConnectivityActions(runtime, store);
installSketchGizmo(runtime, store);
installFeatureOperationsTree(appUI, store);
installFeatureParametersInspector(appUI, store);
installObjectVisibility(appUI, store, runtime);
installObjectLocking(appUI, store);
installObjectTreeScalability(appUI, store);
installProjectLifecycle(appUI, store, runtime);
installProjectSettings(appUI, store, runtime);
installCameraObjectPreview(appUI, runtime);
installInspectorDiagnostics(appUI, store);

applyBuildIdentity();

// Keep existing application bootstrap below this point unchanged.
